import type { Scheme } from '@/types';

export const DEFAULT_SCHEMES: Scheme[] = [
  {
    id: 'scheme-01',
    name: 'Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)',
    description: 'Central sector scheme providing financial support of ₹6,000 per year in three equal installments to all landholding farmer families across India.',
    category: 'Agriculture,Rural & Environment',
    eligibility_criteria: { age_min: 18, age_max: 75, professions: ['Farmer'], income_max: 600000 },
    benefits: '₹6,000 per year directly transferred into bank accounts of eligible farmers.',
    required_documents: ['Aadhaar Card', 'Land Holding Documents', 'Bank Account Details'],
    application_url: 'https://pmkisan.gov.in',
    deadline: null,
    state: null,
    department: 'Ministry of Agriculture and Farmers Welfare',
    age_min: 18,
    age_max: 75,
    income_max: 600000,
    gender_specific: null,
    education_required: null,
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-02',
    name: 'Kanyashree Prakalpa',
    description: 'Conditional cash transfer scheme by West Bengal government to incentivize schooling of teenage girls and delay child marriage.',
    category: 'Education & Learning',
    eligibility_criteria: { age_min: 13, age_max: 19, professions: ['Student'], income_max: 120000 },
    benefits: 'Annual scholarship of ₹1,000 (K1) and one-time grant of ₹25,000 (K2) upon reaching age 18.',
    required_documents: ['Aadhaar Card', 'School Enrollment Certificate', 'Unmarried Declaration', 'Bank Account Details'],
    application_url: 'https://wbkanyashree.gov.in',
    deadline: '2026-12-31',
    state: 'West Bengal',
    department: 'Department of Women & Child Development and Social Welfare, West Bengal',
    age_min: 13,
    age_max: 19,
    income_max: 120000,
    gender_specific: 'Female',
    education_required: 'Secondary',
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-03',
    name: 'Pradhan Mantri Mudra Yojana (PMMY)',
    description: 'Provides collateral-free micro-loans up to ₹10 Lakhs to non-corporate, non-farm small/micro enterprises for business expansion.',
    category: 'Business & Entrepreneurship',
    eligibility_criteria: { age_min: 18, age_max: 65, professions: ['Self Employed', 'Business Owner', 'Working Professional'], income_max: null },
    benefits: 'Shishu (up to ₹50,000), Kishor (₹50,000 to ₹5 Lakhs), and Tarun (₹5 Lakhs to ₹10 Lakhs) loans.',
    required_documents: ['Aadhaar Card', 'PAN Card', 'Business Plan', 'Bank Statement of last 6 months'],
    application_url: 'https://www.mudra.org.in',
    deadline: null,
    state: null,
    department: 'Department of Financial Services, Ministry of Finance',
    age_min: 18,
    age_max: 65,
    income_max: null,
    gender_specific: null,
    education_required: null,
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-04',
    name: 'Post-Matric Scholarship for SC/ST/OBC Students',
    description: 'Financial support to eligible post-secondary students belonging to SC/ST/OBC categories to complete higher education.',
    category: 'Education & Learning',
    eligibility_criteria: { age_min: 16, age_max: 30, professions: ['Student'], income_max: 250000 },
    benefits: 'Full tuition fee reimbursement plus maintenance allowance according to course level.',
    required_documents: ['Aadhaar Card', 'Caste Certificate', 'Income Certificate', 'Mark Sheets', 'Bank Passbook'],
    application_url: 'https://scholarships.gov.in',
    deadline: '2026-11-30',
    state: null,
    department: 'Ministry of Social Justice and Empowerment',
    age_min: 16,
    age_max: 30,
    income_max: 250000,
    gender_specific: null,
    education_required: 'Class 10 Pass',
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-05',
    name: 'Stand Up India Scheme',
    description: 'Facilitates bank loans between ₹10 Lakhs and ₹1 Crore to SC/ST and Women borrowers for setting up greenfield enterprises.',
    category: 'Business & Entrepreneurship',
    eligibility_criteria: { age_min: 18, age_max: 65, professions: ['Business Owner', 'Self Employed'], income_max: null },
    benefits: 'Bank loan between ₹10 Lakhs and ₹1 Crore for manufacturing, services, or trading sectors.',
    required_documents: ['Aadhaar Card', 'PAN Card', 'Caste Certificate (if applicable)', 'Project Report', 'Address Proof'],
    application_url: 'https://www.standupmitra.in',
    deadline: null,
    state: null,
    department: 'Department of Financial Services, Ministry of Finance',
    age_min: 18,
    age_max: 65,
    income_max: null,
    gender_specific: null,
    education_required: null,
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-06',
    name: 'Ayushman Bharat Pradhan Mantri Jan Arogya Yojana (PM-JAY)',
    description: 'World\'s largest health insurance scheme providing ₹5 Lakhs health cover per family per year for secondary and tertiary care hospitalization.',
    category: 'Health & Wellness',
    eligibility_criteria: { age_min: null, age_max: null, professions: ['Working Professional', 'Self Employed', 'Unemployed', 'Farmer', 'Housewife', 'Student'], income_max: 300000 },
    benefits: 'Cashless and paperless access to healthcare services up to ₹5 Lakhs per family per year.',
    required_documents: ['Aadhaar Card', 'Ration Card', 'Family ID / Income Certificate'],
    application_url: 'https://pmjay.gov.in',
    deadline: null,
    state: null,
    department: 'National Health Authority',
    age_min: null,
    age_max: null,
    income_max: 300000,
    gender_specific: null,
    education_required: null,
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-07',
    name: 'Delhi Pension Scheme to Women in Distress (Widow Pension)',
    description: 'Financial assistance to widows, divorced, separated, abandoned, or destitute women residing in Delhi.',
    category: 'Social welfare & Empowerment',
    eligibility_criteria: { age_min: 18, age_max: null, professions: ['Housewife', 'Unemployed', 'Self Employed'], income_max: 100000 },
    benefits: 'Monthly financial assistance of ₹2,500 deposited directly into beneficiary bank account.',
    required_documents: ['Aadhaar Card', 'Death Certificate of Husband / Divorce Papers', 'Delhi Residence Proof', 'Income Certificate'],
    application_url: 'https://edistrict.delhigovt.nic.in',
    deadline: null,
    state: 'Delhi',
    department: 'Delhi Social Welfare Department',
    age_min: 18,
    age_max: null,
    income_max: 100000,
    gender_specific: 'Female',
    education_required: null,
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-08',
    name: 'Dilli Swarojgar Yojna',
    description: 'Provides loans up to ₹5,00,000/- at 6% interest for income-generating self-employment activities in Delhi.',
    category: 'Business & Entrepreneurship',
    eligibility_criteria: { age_min: 18, age_max: 60, professions: ['Self Employed', 'Business Owner', 'Unemployed'], income_max: 300000 },
    benefits: 'Term loan up to ₹5 Lakhs at low interest rate of 6% with easy repayment terms.',
    required_documents: ['Aadhaar Card', 'Project Proposal', 'Delhi Residence Proof', 'Caste/Income Certificate'],
    application_url: 'https://dsfdc.delhi.gov.in',
    deadline: null,
    state: 'Delhi',
    department: 'Delhi Scheduled Castes Financial and Development Corporation (DSFDC)',
    age_min: 18,
    age_max: 60,
    income_max: 300000,
    gender_specific: null,
    education_required: null,
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-09',
    name: 'Krishak Bandhu Scheme',
    description: 'Provides financial security to farmers in West Bengal through direct income support and death benefit assurance.',
    category: 'Agriculture,Rural & Environment',
    eligibility_criteria: { age_min: 18, age_max: 70, professions: ['Farmer'], income_max: null },
    benefits: '₹10,000 per acre per year income support and ₹2,00,000 life insurance cover in case of death.',
    required_documents: ['Aadhaar Card', 'RoR / Land Khatian', 'Bank Account Details'],
    application_url: 'https://krishakbandhu.wb.gov.in',
    deadline: null,
    state: 'West Bengal',
    department: 'Department of Agriculture, West Bengal',
    age_min: 18,
    age_max: 70,
    income_max: null,
    gender_specific: null,
    education_required: null,
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-10',
    name: 'Chief Minister Employment Generation Programme (CMEGP)',
    description: 'Financial assistance and capital subsidy to educated unemployed youth for setting up new self-employment projects in Maharashtra.',
    category: 'Business & Entrepreneurship',
    eligibility_criteria: { age_min: 18, age_max: 45, professions: ['Unemployed', 'Self Employed', 'Business Owner'], income_max: null },
    benefits: 'Project cost up to ₹50 Lakhs (Manufacturing) / ₹10 Lakhs (Service) with 15% to 35% government subsidy.',
    required_documents: ['Aadhaar Card', 'Project Report', 'Educational Qualification Certificate', 'Domicile Certificate of Maharashtra'],
    application_url: 'https://cmegp.mahait.org',
    deadline: null,
    state: 'Maharashtra',
    department: 'Industries Department, Government of Maharashtra',
    age_min: 18,
    age_max: 45,
    income_max: null,
    gender_specific: null,
    education_required: 'Class 7 Pass',
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-11',
    name: 'National Overseas Scholarship for SC Students',
    description: 'Financial assistance for low-income SC, De-notified Nomadic Tribes, and Landless Agricultural Labourers for pursuing Master\'s / Ph.D. abroad.',
    category: 'Education & Learning',
    eligibility_criteria: { age_min: 18, age_max: 35, professions: ['Student'], income_max: 800000 },
    benefits: 'Total tuition fees, living allowance of USD 15,400 / GBP 9,900 annually, visa fees and air passage.',
    required_documents: ['Aadhaar Card', 'Caste Certificate', 'Income Certificate', 'Offer Letter from Top 500 Foreign University'],
    application_url: 'https://nosmsje.gov.in',
    deadline: '2026-10-31',
    state: null,
    department: 'Ministry of Social Justice and Empowerment',
    age_min: 18,
    age_max: 35,
    income_max: 800000,
    gender_specific: null,
    education_required: 'Graduate',
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-12',
    name: 'PM Vishwakarma Scheme',
    description: 'Comprehensive support to traditional artisans and craftspeople engaged in 18 traditional trades like weavers, blacksmiths, carpenters, goldsmiths, and tailors.',
    category: 'Business & Entrepreneurship',
    eligibility_criteria: { age_min: 18, age_max: 70, professions: ['Self Employed', 'Working Professional'], income_max: null },
    benefits: 'Skill training with ₹500/day stipend, ₹15,000 toolkit e-voucher, and collateral-free credit support up to ₹3 Lakhs at 5% interest.',
    required_documents: ['Aadhaar Card', 'Bank Account Details', 'Artisan Verification Card'],
    application_url: 'https://pmvishwakarma.gov.in',
    deadline: null,
    state: null,
    department: 'Ministry of Micro, Small and Medium Enterprises (MSME)',
    age_min: 18,
    age_max: 70,
    income_max: null,
    gender_specific: null,
    education_required: null,
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-13',
    name: 'Pradhan Mantri Matru Vandana Yojana (PMMVY)',
    description: 'Maternity benefit program providing cash incentives to pregnant women and lactating mothers for health and nutrition.',
    category: 'Health & Wellness',
    eligibility_criteria: { age_min: 19, age_max: 45, professions: ['Housewife', 'Unemployed', 'Self Employed', 'Farmer'], income_max: 500000 },
    benefits: 'Direct cash benefit of ₹5,000 in two installments for the first living child.',
    required_documents: ['Aadhaar Card', 'MCP Card (Mother & Child Protection Card)', 'Bank Account Details'],
    application_url: 'https://pmmvy.wcd.gov.in',
    deadline: null,
    state: null,
    department: 'Ministry of Women and Child Development',
    age_min: 19,
    age_max: 45,
    income_max: 500000,
    gender_specific: 'Female',
    education_required: null,
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-14',
    name: 'PM SVANidhi (Street Vendor\'s AtmaNirbhar Nidhi)',
    description: 'Special micro-credit facility providing affordable working capital loans to street vendors to resume livelihoods.',
    category: 'Business & Entrepreneurship',
    eligibility_criteria: { age_min: 18, age_max: 65, professions: ['Self Employed', 'Business Owner'], income_max: 300000 },
    benefits: 'Initial working capital loan up to ₹10,000, enhanced to ₹20,000 and ₹50,000 on timely repayment with 7% interest subsidy.',
    required_documents: ['Aadhaar Card', 'Vending Certificate / Identity Card', 'Bank Passbook'],
    application_url: 'https://pmsvanidhi.mohua.gov.in',
    deadline: null,
    state: null,
    department: 'Ministry of Housing and Urban Affairs',
    age_min: 18,
    age_max: 65,
    income_max: 300000,
    gender_specific: null,
    education_required: null,
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-15',
    name: 'Prime Minister\'s Employment Generation Programme (PMEGP)',
    description: 'Major credit-linked subsidy program aimed at generating self-employment opportunities through establishment of micro-enterprises in non-farm sector.',
    category: 'Business & Entrepreneurship',
    eligibility_criteria: { age_min: 18, age_max: 60, professions: ['Unemployed', 'Self Employed', 'Business Owner'], income_max: null },
    benefits: 'Subsidy up to 35% of project cost (Max Project Cost ₹50 Lakhs for Manufacturing, ₹20 Lakhs for Services).',
    required_documents: ['Aadhaar Card', 'Project Report', 'Highest Educational Certificate', 'EDP Training Certificate'],
    application_url: 'https://www.kviconline.gov.in/pmegpeportal',
    deadline: null,
    state: null,
    department: 'Khadi and Village Industries Commission (KVIC)',
    age_min: 18,
    age_max: 60,
    income_max: null,
    gender_specific: null,
    education_required: 'Class 8 Pass',
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-16',
    name: 'Atal Pension Yojana (APY)',
    description: 'Pension scheme targeted at workers in the unorganized sector providing guaranteed monthly pension after age 60.',
    category: 'Social welfare & Empowerment',
    eligibility_criteria: { age_min: 18, age_max: 40, professions: ['Self Employed', 'Working Professional', 'Farmer', 'Housewife', 'Unemployed'], income_max: null },
    benefits: 'Guaranteed minimum monthly pension ranging from ₹1,000 to ₹5,000 after reaching age 60.',
    required_documents: ['Aadhaar Card', 'Bank Account linked with Mobile Number'],
    application_url: 'https://www.npscra.nsdl.co.in',
    deadline: null,
    state: null,
    department: 'Pension Fund Regulatory and Development Authority (PFRDA)',
    age_min: 18,
    age_max: 40,
    income_max: null,
    gender_specific: null,
    education_required: null,
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-17',
    name: 'Pradhan Mantri Kisan Maandhan Yojana (PM-KMY)',
    description: 'Voluntary and contributory pension scheme for small and marginal farmers across India.',
    category: 'Agriculture,Rural & Environment',
    eligibility_criteria: { age_min: 18, age_max: 40, professions: ['Farmer'], income_max: null },
    benefits: 'Fixed monthly pension of ₹3,000 upon attaining 60 years of age.',
    required_documents: ['Aadhaar Card', 'Savings Bank Account', 'Khasra/Khatauni Land Record'],
    application_url: 'https://pmkmy.gov.in',
    deadline: null,
    state: null,
    department: 'Ministry of Agriculture and Farmers Welfare',
    age_min: 18,
    age_max: 40,
    income_max: null,
    gender_specific: null,
    education_required: null,
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-18',
    name: 'Central Sector Scheme of Scholarship for College and University Students',
    description: 'Financial support to meritorious students from low-income families to meet day-to-day expenses while pursuing higher studies.',
    category: 'Education & Learning',
    eligibility_criteria: { age_min: 17, age_max: 25, professions: ['Student'], income_max: 450000 },
    benefits: '₹12,000 per annum at Graduation level for first 3 years and ₹20,000 per annum at Post-Graduation level.',
    required_documents: ['Aadhaar Card', 'Class 12 Marksheet', 'Income Certificate', 'College Admission Proof'],
    application_url: 'https://scholarships.gov.in',
    deadline: '2026-12-15',
    state: null,
    department: 'Department of Higher Education, Ministry of Education',
    age_min: 17,
    age_max: 25,
    income_max: 450000,
    gender_specific: null,
    education_required: 'Class 12 Pass',
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-19',
    name: 'Pradhan Mantri Fasal Bima Yojana (PMFBY)',
    description: 'Comprehensive crop insurance covering yield losses due to non-preventable natural risks from pre-sowing to post-harvest.',
    category: 'Agriculture,Rural & Environment',
    eligibility_criteria: { age_min: 18, age_max: 75, professions: ['Farmer'], income_max: null },
    benefits: 'Financial cover against crop failure due to drought, flood, pests, or disease with low farmer premium rates (1.5% to 2%).',
    required_documents: ['Aadhaar Card', 'Land Possession Certificate / Sowing Certificate', 'Bank Account Details'],
    application_url: 'https://pmfby.gov.in',
    deadline: null,
    state: null,
    department: 'Ministry of Agriculture and Farmers Welfare',
    age_min: 18,
    age_max: 75,
    income_max: null,
    gender_specific: null,
    education_required: null,
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-20',
    name: 'National Apprenticeship Promotion Scheme (NAPS)',
    description: 'Promotes apprenticeship training and offers stipend support to youth joining technical and vocational industrial training.',
    category: 'Employment & Skill Development',
    eligibility_criteria: { age_min: 14, age_max: 35, professions: ['Student', 'Unemployed'], income_max: null },
    benefits: 'Government shares 25% of prescribed stipend up to ₹1,500 per month per apprentice directly into bank accounts.',
    required_documents: ['Aadhaar Card', 'Educational Certificate', 'Bank Passbook'],
    application_url: 'https://www.apprenticeshipindia.gov.in',
    deadline: null,
    state: null,
    department: 'Ministry of Skill Development and Entrepreneurship',
    age_min: 14,
    age_max: 35,
    income_max: null,
    gender_specific: null,
    education_required: 'Class 5 Pass',
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-21',
    name: 'Delhi Arogya Kosh (DAK)',
    description: 'Provides financial assistance up to ₹5 Lakhs to needy patients residing in Delhi for specialized medical treatment in empaneled hospitals.',
    category: 'Health & Wellness',
    eligibility_criteria: { age_min: null, age_max: null, professions: ['Working Professional', 'Self Employed', 'Unemployed', 'Farmer', 'Housewife', 'Student'], income_max: 300000 },
    benefits: 'Financial coverage for surgeries, diagnostic tests, and treatments in Delhi government/private hospitals.',
    required_documents: ['Aadhaar Card', 'Delhi Voter ID', 'Income Certificate', 'Hospital Treatment Estimate'],
    application_url: 'https://health.delhi.gov.in',
    deadline: null,
    state: 'Delhi',
    department: 'Directorate General of Health Services, Delhi',
    age_min: null,
    age_max: null,
    income_max: 300000,
    gender_specific: null,
    education_required: null,
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-22',
    name: 'Delhi Higher Education Guarantee Scheme',
    description: 'Credit guarantee for collateral-free education loans up to ₹10 Lakhs for students pursuing higher education in Delhi.',
    category: 'Education & Learning',
    eligibility_criteria: { age_min: 16, age_max: 28, professions: ['Student'], income_max: null },
    benefits: 'Bank loan up to ₹10 Lakhs without any collateral security or third-party guarantee.',
    required_documents: ['Aadhaar Card', 'Admission Letter', 'Fee Structure', 'Class 10 & 12 Marksheets'],
    application_url: 'https://higheredugrant.delhi.gov.in',
    deadline: null,
    state: 'Delhi',
    department: 'Higher Education Department, Government of Delhi',
    age_min: 16,
    age_max: 28,
    income_max: null,
    gender_specific: null,
    education_required: 'Class 12 Pass',
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-23',
    name: 'PM YASASVI Top Class School Scholarship',
    description: 'Top class scholarship scheme for vibrant India targeting meritorious students from OBC, EBC, and DNT categories.',
    category: 'Education & Learning',
    eligibility_criteria: { age_min: 13, age_max: 19, professions: ['Student'], income_max: 250000 },
    benefits: 'Scholarship of ₹75,000 per annum for Class 9 & 10 and ₹1,25,000 per annum for Class 11 & 12.',
    required_documents: ['Aadhaar Card', 'OBC/EBC Category Certificate', 'Income Certificate', 'School Bonafide Certificate'],
    application_url: 'https://yet.nta.ac.in',
    deadline: '2026-11-15',
    state: null,
    department: 'Ministry of Social Justice and Empowerment',
    age_min: 13,
    age_max: 19,
    income_max: 250000,
    gender_specific: null,
    education_required: 'Class 8 Pass',
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-24',
    name: 'Sabooj Sathi Bicycle Distribution Scheme',
    description: 'Distribution of bicycles to students of Classes 9 to 12 in West Bengal to facilitate school attendance and reduce dropouts.',
    category: 'Education & Learning',
    eligibility_criteria: { age_min: 13, age_max: 18, professions: ['Student'], income_max: null },
    benefits: 'Free brand new bicycle to high school students studying in government/aided schools in West Bengal.',
    required_documents: ['Student ID Card', 'Aadhaar Card', 'School Admission Record'],
    application_url: 'https://wbsaboojsathi.gov.in',
    deadline: null,
    state: 'West Bengal',
    department: 'Backward Classes Welfare Department, West Bengal',
    age_min: 13,
    age_max: 18,
    income_max: null,
    gender_specific: null,
    education_required: 'Secondary',
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-25',
    name: 'Lakshmir Bhandar Scheme',
    description: 'Financial support scheme for female heads of households in West Bengal to assure basic monthly income support.',
    category: 'Social welfare & Empowerment',
    eligibility_criteria: { age_min: 25, age_max: 60, professions: ['Housewife', 'Unemployed', 'Self Employed', 'Farmer'], income_max: 200000 },
    benefits: 'Direct bank transfer of ₹1,000/month for General category and ₹1,200/month for SC/ST women.',
    required_documents: ['Aadhaar Card', 'Swasthya Sathi Card', 'Caste Certificate (if SC/ST)', 'Bank Passbook'],
    application_url: 'https://duaresarkar.wb.gov.in',
    deadline: null,
    state: 'West Bengal',
    department: 'Department of Women & Child Development and Social Welfare, West Bengal',
    age_min: 25,
    age_max: 60,
    income_max: 200000,
    gender_specific: 'Female',
    education_required: null,
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-26',
    name: 'West Bengal Student Credit Card Scheme',
    description: 'Soft education loan scheme providing up to ₹10 Lakhs for students pursuing higher secondary, diploma, degree or doctoral studies.',
    category: 'Education & Learning',
    eligibility_criteria: { age_min: 16, age_max: 40, professions: ['Student'], income_max: null },
    benefits: 'Collateral-free loan up to ₹10 Lakhs at 4% simple interest rate with 15-year repayment window.',
    required_documents: ['Aadhaar Card', 'Admission Receipt', 'Course Fee Structure', 'PAN Card of Student & Co-borrower'],
    application_url: 'https://wbscc.wb.gov.in',
    deadline: null,
    state: 'West Bengal',
    department: 'Higher Education Department, West Bengal',
    age_min: 16,
    age_max: 40,
    income_max: null,
    gender_specific: null,
    education_required: 'Secondary',
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-27',
    name: 'Swasthya Sathi Health Insurance Scheme',
    description: 'Universal health coverage scheme providing basic health protection for secondary and tertiary care in West Bengal.',
    category: 'Health & Wellness',
    eligibility_criteria: { age_min: null, age_max: null, professions: ['Working Professional', 'Self Employed', 'Unemployed', 'Farmer', 'Housewife', 'Student'], income_max: null },
    benefits: 'Basic health cover up to ₹5 Lakhs per family per annum across 1,500+ empaneled hospitals.',
    required_documents: ['Swasthya Sathi Smart Card', 'Aadhaar Card', 'Family Member Details'],
    application_url: 'https://swasthyasathi.gov.in',
    deadline: null,
    state: 'West Bengal',
    department: 'Health & Family Welfare Department, West Bengal',
    age_min: null,
    age_max: null,
    income_max: null,
    gender_specific: null,
    education_required: null,
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-28',
    name: 'Majhi Kanya Bhagyashree Scheme',
    description: 'Financial incentive scheme in Maharashtra to improve sex ratio and encourage girl child birth and education.',
    category: 'Social welfare & Empowerment',
    eligibility_criteria: { age_min: 0, age_max: 18, professions: ['Housewife', 'Unemployed', 'Farmer', 'Student'], income_max: 750000 },
    benefits: '₹50,000 deposited in bank account of girl child at birth, accessible upon completing age 18 and Class 10.',
    required_documents: ['Birth Certificate of Girl Child', 'Aadhaar Card of Parents', 'Sterilization Certificate / Family Income Proof'],
    application_url: 'https://womenchild.maharashtra.gov.in',
    deadline: null,
    state: 'Maharashtra',
    department: 'Women and Child Development Department, Maharashtra',
    age_min: 0,
    age_max: 18,
    income_max: 750000,
    gender_specific: 'Female',
    education_required: null,
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-29',
    name: 'Sanjay Gandhi Niradhar An अनुदान Yojana',
    description: 'Monthly financial assistance to destitute persons, blind, disabled, orphans, and terminally ill individuals in Maharashtra.',
    category: 'Social welfare & Empowerment',
    eligibility_criteria: { age_min: 18, age_max: 65, professions: ['Unemployed', 'Housewife'], income_max: 21000 },
    benefits: 'Monthly financial grant of ₹1,000 to ₹1,200 per beneficiary.',
    required_documents: ['Aadhaar Card', 'Disability / Medical Certificate', 'Income Certificate', 'Maharashtra Domicile Certificate'],
    application_url: 'https://sanjaygandhiniradhar.maharashtra.gov.in',
    deadline: null,
    state: 'Maharashtra',
    department: 'Social Justice and Special Assistance Department, Maharashtra',
    age_min: 18,
    age_max: 65,
    income_max: 21000,
    gender_specific: null,
    education_required: null,
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-30',
    name: 'Pradhan Mantri Kaushal Vikas Yojana (PMKVY 4.0)',
    description: 'Flagship skill certification scheme enabling Indian youth to take up industry-relevant skill training to secure better livelihoods.',
    category: 'Employment & Skill Development',
    eligibility_criteria: { age_min: 15, age_max: 45, professions: ['Unemployed', 'Student', 'Self Employed'], income_max: null },
    benefits: 'Free short-term skill training, assessment & government skill certification with placement assistance.',
    required_documents: ['Aadhaar Card', 'Educational Certificate', 'Bank Account Details'],
    application_url: 'https://www.pmkvyofficial.org',
    deadline: null,
    state: null,
    department: 'Ministry of Skill Development and Entrepreneurship',
    age_min: 15,
    age_max: 45,
    income_max: null,
    gender_specific: null,
    education_required: null,
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-31',
    name: 'Sukanya Samriddhi Yojana (SSY)',
    description: 'Small deposit savings scheme targeted for girl children offering high interest rates and tax benefits under Section 80C.',
    category: 'Social welfare & Empowerment',
    eligibility_criteria: { age_min: 0, age_max: 10, professions: ['Student'], income_max: null },
    benefits: '8.2% annual interest rate compounded yearly with tax-free returns for higher education and marriage.',
    required_documents: ['Birth Certificate of Girl Child', 'Aadhaar Card of Parent/Guardian', 'Address Proof'],
    application_url: 'https://www.indiapost.gov.in',
    deadline: null,
    state: null,
    department: 'Department of Posts, Ministry of Communications',
    age_min: 0,
    age_max: 10,
    income_max: null,
    gender_specific: 'Female',
    education_required: null,
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-32',
    name: 'Pradhan Mantri Kusum Yojana (Solar Pump Subsidy)',
    description: 'Promotes solar pump installation and solarization of grid-connected agricultural pumps for energy security of farmers.',
    category: 'Agriculture,Rural & Environment',
    eligibility_criteria: { age_min: 18, age_max: 75, professions: ['Farmer'], income_max: null },
    benefits: '60% government subsidy (30% Central + 30% State) for installing standalone solar agricultural pumps.',
    required_documents: ['Aadhaar Card', 'Land Ownership Records', 'Bank Passbook', 'Electricity Connection Details'],
    application_url: 'https://pmkusum.mnre.gov.in',
    deadline: null,
    state: null,
    department: 'Ministry of New and Renewable Energy (MNRE)',
    age_min: 18,
    age_max: 75,
    income_max: null,
    gender_specific: null,
    education_required: null,
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-33',
    name: 'Startup India Seed Fund Scheme (SISFS)',
    description: 'Financial assistance to early-stage startups for proof of concept, prototype development, product trials, and market entry.',
    category: 'Business & Entrepreneurship',
    eligibility_criteria: { age_min: 18, age_max: 60, professions: ['Business Owner', 'Self Employed'], income_max: null },
    benefits: 'Grants up to ₹20 Lakhs for prototype validation & convertible debentures up to ₹50 Lakhs for commercialization.',
    required_documents: ['DPIIT Startup Recognition Certificate', 'Business Plan Pitch Deck', 'Company Registration Proof'],
    application_url: 'https://seedfund.startupindia.gov.in',
    deadline: null,
    state: null,
    department: 'DPIIT, Ministry of Commerce and Industry',
    age_min: 18,
    age_max: 60,
    income_max: null,
    gender_specific: null,
    education_required: null,
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-34',
    name: 'National Means-cum-Merit Scholarship Scheme (NMMSS)',
    description: 'Awarding scholarships to meritorious students of economically weaker sections to arrest dropout after Class 8.',
    category: 'Education & Learning',
    eligibility_criteria: { age_min: 13, age_max: 17, professions: ['Student'], income_max: 350000 },
    benefits: 'Scholarship of ₹12,000 per annum (₹1,000/month) for Class 9 to Class 12.',
    required_documents: ['Aadhaar Card', 'Class 8 Report Card', 'Income Certificate', 'Bank Account Details'],
    application_url: 'https://scholarships.gov.in',
    deadline: '2026-11-30',
    state: null,
    department: 'Department of School Education and Literacy, Ministry of Education',
    age_min: 13,
    age_max: 17,
    income_max: 350000,
    gender_specific: null,
    education_required: 'Class 8 Pass',
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-35',
    name: 'Banglar Awaas Yojana (BAY)',
    description: 'State housing scheme providing financial support to homeless households and families living in kutcha houses in West Bengal.',
    category: 'Housing & Shelter',
    eligibility_criteria: { age_min: 18, age_max: 75, professions: ['Farmer', 'Working Professional', 'Unemployed', 'Self Employed'], income_max: 150000 },
    benefits: 'Financial assistance of ₹1,20,000 for constructing a permanent pucca house with toilet and drinking water.',
    required_documents: ['Aadhaar Card', 'Job Card / BPL Certificate', 'Land Proof', 'Bank Account Details'],
    application_url: 'https://wb.gov.in',
    deadline: null,
    state: 'West Bengal',
    department: 'Panchayat & Rural Development Department, West Bengal',
    age_min: 18,
    age_max: 75,
    income_max: 150000,
    gender_specific: null,
    education_required: null,
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-36',
    name: 'Delhi Free Bus Travel Scheme for Women',
    description: 'Provides single-journey pink tickets for free travel in DTC city and cluster buses across Delhi NCR for all female passengers.',
    category: 'Social welfare & Empowerment',
    eligibility_criteria: { age_min: 5, age_max: 85, professions: ['Housewife', 'Student', 'Working Professional', 'Self Employed', 'Unemployed'], income_max: null },
    benefits: '100% fare waiver for women travelling in all public transit DTC & Cluster buses in Delhi.',
    required_documents: ['Identity Proof (Optional for conductor ticket issuance)'],
    application_url: 'https://dtc.delhi.gov.in',
    deadline: null,
    state: 'Delhi',
    department: 'Transport Department, Government of NCT of Delhi',
    age_min: 5,
    age_max: 85,
    income_max: null,
    gender_specific: 'Female',
    education_required: null,
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-37',
    name: 'Pradhan Mantri Gramin Awaas Yojana (PMAY-G)',
    description: 'Financial assistance to rural houseless families and those living in dilapidated houses for construction of pucca house.',
    category: 'Housing & Shelter',
    eligibility_criteria: { age_min: 18, age_max: 75, professions: ['Farmer', 'Unemployed', 'Self Employed', 'Working Professional'], income_max: 180000 },
    benefits: 'Direct financial assistance of ₹1.20 Lakh in plains and ₹1.30 Lakh in hilly/difficult areas.',
    required_documents: ['Aadhaar Card', 'SECC Family Registration Number', 'Bank Passbook', 'Land Ownership Proof'],
    application_url: 'https://pmayg.nic.in',
    deadline: null,
    state: null,
    department: 'Ministry of Rural Development',
    age_min: 18,
    age_max: 75,
    income_max: 180000,
    gender_specific: null,
    education_required: null,
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-38',
    name: 'Mahila Samman Savings Certificate',
    description: 'Special small savings deposit scheme empowering female investors with attractive interest rates and partial withdrawal options.',
    category: 'Social welfare & Empowerment',
    eligibility_criteria: { age_min: 10, age_max: 85, professions: ['Housewife', 'Working Professional', 'Self Employed', 'Student'], income_max: null },
    benefits: 'High fixed interest rate of 7.5% per annum for a 2-year tenure with maximum deposit limit of ₹2 Lakhs.',
    required_documents: ['Aadhaar Card', 'PAN Card', 'Passport Photograph'],
    application_url: 'https://www.indiapost.gov.in',
    deadline: null,
    state: null,
    department: 'Department of Posts, Ministry of Finance',
    age_min: 10,
    age_max: 85,
    income_max: null,
    gender_specific: 'Female',
    education_required: null,
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-39',
    name: 'Soil Health Card Scheme',
    description: 'Issuance of soil health cards to farmers every 3 years containing nutrient status of soil and crop-wise fertilizer recommendations.',
    category: 'Agriculture,Rural & Environment',
    eligibility_criteria: { age_min: 18, age_max: 80, professions: ['Farmer'], income_max: null },
    benefits: 'Free soil testing & tailored soil nutrient recommendations to boost crop productivity and reduce fertilizer cost.',
    required_documents: ['Aadhaar Card', 'Land Holding Record / Khasra Number'],
    application_url: 'https://soilhealth.dac.gov.in',
    deadline: null,
    state: null,
    department: 'Ministry of Agriculture and Farmers Welfare',
    age_min: 18,
    age_max: 80,
    income_max: null,
    gender_specific: null,
    education_required: null,
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-40',
    name: 'National SC-ST Hub Scheme',
    description: 'Promotes entrepreneurship among SC/ST communities by offering capacity building, market access, and vendor development.',
    category: 'Business & Entrepreneurship',
    eligibility_criteria: { age_min: 18, age_max: 65, professions: ['Self Employed', 'Business Owner'], income_max: null },
    benefits: 'Subsidized participation in trade fairs, financial assistance for quality certification, and 4% mandatory procurement reservation.',
    required_documents: ['Aadhaar Card', 'Caste Certificate', 'Udyam Registration Certificate', 'PAN Card'],
    application_url: 'https://www.scsthub.in',
    deadline: null,
    state: null,
    department: 'Ministry of Micro, Small and Medium Enterprises (MSME)',
    age_min: 18,
    age_max: 65,
    income_max: null,
    gender_specific: null,
    education_required: null,
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-41',
    name: 'Shravanbal Seva State Pension Scheme',
    description: 'Monthly financial pension to destitute elderly citizens aged 65 years and above in Maharashtra.',
    category: 'Social welfare & Empowerment',
    eligibility_criteria: { age_min: 65, age_max: 95, professions: ['Unemployed', 'Housewife', 'Farmer'], income_max: 21000 },
    benefits: 'Monthly pension of ₹1,000 to ₹1,500 deposited directly into senior citizen bank accounts.',
    required_documents: ['Aadhaar Card', 'Age Certificate / Voter ID', 'Income Certificate', 'Maharashtra Domicile Proof'],
    application_url: 'https://sanjaygandhiniradhar.maharashtra.gov.in',
    deadline: null,
    state: 'Maharashtra',
    department: 'Social Justice and Special Assistance Department, Maharashtra',
    age_min: 65,
    age_max: 95,
    income_max: 21000,
    gender_specific: null,
    education_required: null,
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-42',
    name: 'Deendayal Antyodaya Yojana - National Rural Livelihoods Mission (DAY-NRLM)',
    description: 'Organizing rural poor women into Self Help Groups (SHGs) and providing continuous financial and credit support for sustainable livelihoods.',
    category: 'Social welfare & Empowerment',
    eligibility_criteria: { age_min: 18, age_max: 60, professions: ['Housewife', 'Self Employed', 'Farmer', 'Unemployed'], income_max: 150000 },
    benefits: 'Revolving fund of ₹20,000 to ₹30,000 per SHG and collateral-free bank credit up to ₹10 Lakhs.',
    required_documents: ['Aadhaar Card', 'SHG Registration Proof', 'Bank Account Details'],
    application_url: 'https://nrlm.gov.in',
    deadline: null,
    state: null,
    department: 'Ministry of Rural Development',
    age_min: 18,
    age_max: 60,
    income_max: 150000,
    gender_specific: 'Female',
    education_required: null,
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-43',
    name: 'Pradhan Mantri Jan Dhan Yojana (PMJDY)',
    description: 'National mission for financial inclusion ensuring universal access to banking accounts, credit, remittance, and insurance.',
    category: 'Social welfare & Empowerment',
    eligibility_criteria: { age_min: 10, age_max: 75, professions: ['Working Professional', 'Self Employed', 'Unemployed', 'Farmer', 'Housewife', 'Student'], income_max: null },
    benefits: 'Zero balance savings account, free RuPay debit card with ₹2 Lakh accident insurance cover and ₹10,000 overdraft facility.',
    required_documents: ['Aadhaar Card', 'Passport Photo'],
    application_url: 'https://pmjdy.gov.in',
    deadline: null,
    state: null,
    department: 'Department of Financial Services, Ministry of Finance',
    age_min: 10,
    age_max: 75,
    income_max: null,
    gender_specific: null,
    education_required: null,
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-44',
    name: 'Senior Citizen Savings Scheme (SCSS)',
    description: 'Government-backed savings scheme for individuals aged 60+ offering safety, regular quarterly income, and tax benefits.',
    category: 'Social welfare & Empowerment',
    eligibility_criteria: { age_min: 60, age_max: 99, professions: ['Working Professional', 'Unemployed', 'Self Employed'], income_max: null },
    benefits: 'Guaranteed 8.2% quarterly interest rate on deposits up to ₹30 Lakhs.',
    required_documents: ['Aadhaar Card', 'PAN Card', 'Age Proof Certificate', 'Bank Passbook'],
    application_url: 'https://www.nsiindia.gov.in',
    deadline: null,
    state: null,
    department: 'Department of Economic Affairs, Ministry of Finance',
    age_min: 60,
    age_max: 99,
    income_max: null,
    gender_specific: null,
    education_required: null,
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-45',
    name: 'Delhi Disadvantaged Student Free Coaching Scheme (Jai Bhim Mukhyamantri Pratibha Vikas Yojana)',
    description: 'Free entrance exam coaching for SC/ST/OBC/EWS students in Delhi preparing for competitive exams like UPSC, NEET, JEE, and Banking.',
    category: 'Education & Learning',
    eligibility_criteria: { age_min: 15, age_max: 30, professions: ['Student'], income_max: 800000 },
    benefits: '100% free coaching fees paid directly to empaneled institutes plus monthly stipend of ₹2,500 for books & transport.',
    required_documents: ['Aadhaar Card', 'Class 10 & 12 Marksheets', 'Category / Income Certificate', 'Delhi Residence Proof'],
    application_url: 'https://scstwelfare.delhi.gov.in',
    deadline: '2026-10-15',
    state: 'Delhi',
    department: 'Department for Welfare of SC/ST/OBC, Delhi',
    age_min: 15,
    age_max: 30,
    income_max: 800000,
    gender_specific: null,
    education_required: 'Secondary',
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-46',
    name: 'PM Suraksha Bima Yojana (PMSBY)',
    description: 'Accidental insurance scheme offering risk coverage for accidental death and full disability at nominal annual premium.',
    category: 'Health & Wellness',
    eligibility_criteria: { age_min: 18, age_max: 70, professions: ['Working Professional', 'Self Employed', 'Unemployed', 'Farmer', 'Housewife', 'Student'], income_max: null },
    benefits: '₹2 Lakhs accidental death & full disability cover for an annual premium of just ₹20.',
    required_documents: ['Aadhaar Card', 'Bank Account Consent Form'],
    application_url: 'https://www.jansuraksha.gov.in',
    deadline: null,
    state: null,
    department: 'Department of Financial Services, Ministry of Finance',
    age_min: 18,
    age_max: 70,
    income_max: null,
    gender_specific: null,
    education_required: null,
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-47',
    name: 'PM Jeevan Jyoti Bima Yojana (PMJJBY)',
    description: 'Life insurance scheme renewable annually offering life cover for death due to any cause to bank account holders.',
    category: 'Health & Wellness',
    eligibility_criteria: { age_min: 18, age_max: 50, professions: ['Working Professional', 'Self Employed', 'Unemployed', 'Farmer', 'Housewife', 'Student'], income_max: null },
    benefits: 'Life insurance cover of ₹2 Lakhs payable to nominee upon member death due to any reason.',
    required_documents: ['Aadhaar Card', 'Bank Auto-Debit Authorization'],
    application_url: 'https://www.jansuraksha.gov.in',
    deadline: null,
    state: null,
    department: 'Department of Financial Services, Ministry of Finance',
    age_min: 18,
    age_max: 50,
    income_max: null,
    gender_specific: null,
    education_required: null,
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-48',
    name: 'PM Mega Integrated Textile Region and Apparel (PM MITRA)',
    description: 'World-class industrial parks boosting textile manufacturing, exports, and self-employment opportunities.',
    category: 'Business & Entrepreneurship',
    eligibility_criteria: { age_min: 18, age_max: 65, professions: ['Business Owner', 'Self Employed'], income_max: null },
    benefits: 'State-of-the-art infrastructure, logistics support, and capital subsidies up to ₹300 Crores per park.',
    required_documents: ['Aadhaar Card', 'Business Registration', 'Project Plan'],
    application_url: 'https://texmin.nic.in',
    deadline: null,
    state: null,
    department: 'Ministry of Textiles',
    age_min: 18,
    age_max: 65,
    income_max: null,
    gender_specific: null,
    education_required: null,
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-49',
    name: 'Kisan Credit Card (KCC) Scheme',
    description: 'Adequate and timely credit support to farmers from banking system for agricultural inputs and cultivation needs.',
    category: 'Agriculture,Rural & Environment',
    eligibility_criteria: { age_min: 18, age_max: 75, professions: ['Farmer'], income_max: null },
    benefits: 'Flexible credit limit up to ₹3 Lakhs at concessional interest rate of 4% per annum upon prompt repayment.',
    required_documents: ['Aadhaar Card', 'Land Ownership Certificate', 'Crop Sowing Proof'],
    application_url: 'https://www.nabard.org',
    deadline: null,
    state: null,
    department: 'NABARD & Ministry of Agriculture',
    age_min: 18,
    age_max: 75,
    income_max: null,
    gender_specific: null,
    education_required: null,
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'scheme-50',
    name: 'Pradhan Mantri Awas Yojana - Urban (PMAY-U 2.0)',
    description: 'Providing all-weather pucca houses to all eligible urban households in EWS, LIG, and MIG categories.',
    category: 'Housing & Shelter',
    eligibility_criteria: { age_min: 18, age_max: 75, professions: ['Working Professional', 'Self Employed', 'Unemployed', 'Farmer', 'Housewife'], income_max: 600000 },
    benefits: 'Interest subsidy up to ₹2.67 Lakhs on housing loans for first-time urban home buyers.',
    required_documents: ['Aadhaar Card', 'Income Certificate', 'Affidavit of No Pucca House', 'Bank Loan Approval Letter'],
    application_url: 'https://pmaymis.gov.in',
    deadline: null,
    state: null,
    department: 'Ministry of Housing and Urban Affairs',
    age_min: 18,
    age_max: 75,
    income_max: 600000,
    gender_specific: null,
    education_required: null,
    embedding: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
];
