-- Add comprehensive schemes from Delhi, West Bengal, and Maharashtra with proper UUIDs

-- Delhi Schemes
INSERT INTO schemes (name, description, category, state, benefits, required_documents, application_url, eligibility_criteria, department) VALUES
('Accidental Death Assistance for Construction Workers', 'Welfare scheme that provides financial assistance of ₹2,00,000/- to the nominees/dependents of members in case death is due to an accident.', 'Social Security', 'Delhi', '₹2,00,000/- financial assistance', ARRAY['Death Certificate', 'Registration Certificate', 'Nominee Details'], 'https://www.myscheme.gov.in/schemes/adacw', '{"target_group": ["Construction Workers"], "profession": ["Working Professional"]}'::jsonb, 'Delhi Building and Other Construction Workers Welfare Board'),

('Artisan Promotion', 'Provides artisans opportunities to participate in national fairs and exhibitions with financial support for participation fees, lodging, boarding, and stipends.', 'Entrepreneurship', 'Delhi', 'Financial support for fairs, exhibitions, lodging, and stipends', ARRAY['Artisan Certificate', 'Identity Proof', 'Bank Details'], 'https://www.myscheme.gov.in/schemes/ap', '{"target_group": ["Scheduled Castes", "OBC", "Minorities"], "profession": ["Self Employed", "Business Owner"]}'::jsonb, 'DSFDC Delhi'),

('Big Loan Scheme Delhi', 'Provides term loans up to ₹5,00,000/- for income-generating activities to SC, OBC, Minorities, Safai Karamcharis, and PwDs.', 'Entrepreneurship', 'Delhi', 'Term loans up to ₹5,00,000/-', ARRAY['Income Certificate', 'Caste Certificate', 'Business Plan'], 'https://www.myscheme.gov.in/schemes/bls', '{"target_group": ["SC", "OBC", "Minorities", "PwD"], "profession": ["Self Employed", "Business Owner", "Unemployed"], "income_max": 300000}'::jsonb, 'DSFDC Delhi'),

('Delhi Arogya Kosh', 'Provides financial assistance to needy patients for treatment in Government Hospitals run by Delhi or Central Government.', 'Healthcare', 'Delhi', 'Financial assistance for medical treatment', ARRAY['Medical Certificate', 'Income Certificate', 'Hospital Bills'], 'https://www.myscheme.gov.in/schemes/dak', '{"target_group": ["All Citizens"], "income_max": 200000}'::jsonb, 'Health Department Delhi'),

('Delhi Arogya Nidhi', 'Financial assistance up to ₹1.5 lakhs to needy patients with National Food Security Cards for treatment in Government hospitals.', 'Healthcare', 'Delhi', 'Up to ₹1.5 lakhs for medical treatment', ARRAY['National Food Security Card', 'Medical Certificate', 'Hospital Bills'], 'https://www.myscheme.gov.in/schemes/dan', '{"target_group": ["NFSC Holders"]}'::jsonb, 'Health Department Delhi'),

('Delhi Pension for Women in Distress', 'Social security financial assistance to widows, divorced, separated, abandoned or destitute women aged 18+ who lack adequate means of subsistence.', 'Social Security', 'Delhi', 'Monthly pension', ARRAY['Age Proof', 'Income Certificate', 'Widow/Divorce Certificate'], 'https://www.myscheme.gov.in/schemes/dpswdwp', '{"target_group": ["Widows", "Divorced Women"], "age_min": 18, "gender_specific": "Female", "profession": ["Housewife", "Unemployed"]}'::jsonb, 'Social Welfare Department Delhi'),

('Education Assistance for Construction Workers Children', 'Scholarship to children of construction workers for education from school to professional courses.', 'Education', 'Delhi', 'Scholarships for various education levels', ARRAY['School Certificate', 'Registration Certificate', 'Mark Sheets'], 'https://www.myscheme.gov.in/schemes/edftcw', '{"target_group": ["Construction Workers Children"], "profession": ["Student"]}'::jsonb, 'Delhi BOCW Welfare Board'),

('Dilli Swarojgar Yojna', 'Loans up to ₹5,00,000/- at 6% interest for income-generating activities for SC, ST, OBC, and Minority communities.', 'Employment', 'Delhi', 'Loans up to ₹5 lakhs at 6% interest', ARRAY['Income Certificate', 'Caste Certificate', 'Business Plan'], 'https://www.myscheme.gov.in/schemes/dsy', '{"target_group": ["SC", "ST", "OBC", "Minorities"], "profession": ["Self Employed", "Business Owner", "Unemployed"]}'::jsonb, 'Delhi Government');

-- West Bengal Schemes
INSERT INTO schemes (name, description, category, state, benefits, required_documents, application_url, eligibility_criteria, department, age_min, age_max, income_max) VALUES
('Banglar Awaas Yojana', 'Financial assistance to houseless households and those in kutcha houses to build pucca houses with essential amenities.', 'Housing', 'West Bengal', 'Financial assistance for pucca house with toilet', ARRAY['Income Certificate', 'Land Documents', 'Identity Proof'], 'https://www.myscheme.gov.in/schemes/bay', '{"target_group": ["Houseless", "Kutcha House Owners"]}'::jsonb, 'Housing Department West Bengal', NULL, NULL, 200000),

('Krishak Bandhu Scheme', 'Financial security to farmers: ₹5,000/- per acre annually + ₹2,00,000/- death benefit for small and marginal farmers.', 'Agriculture', 'West Bengal', '₹5,000/- per acre per year + death benefit', ARRAY['Land Records', 'Identity Proof', 'Bank Details'], 'https://www.myscheme.gov.in/schemes/kbs', '{"target_group": ["Small Farmers", "Marginal Farmers"], "profession": ["Farmer"]}'::jsonb, 'Agriculture Department West Bengal', NULL, NULL, NULL),

('Lakshmir Bhandar Scheme', 'Monthly financial assistance to women aged 25-60 from economically weaker sections enrolled in Swasthya Sathi for empowerment.', 'Women Empowerment', 'West Bengal', 'Monthly financial assistance', ARRAY['Age Proof', 'Income Certificate', 'Swasthya Sathi Card'], 'https://www.myscheme.gov.in/schemes/lbs-wb', '{"target_group": ["Women"], "profession": ["Housewife", "Working Professional"]}'::jsonb, 'Social Welfare West Bengal', 25, 60, 250000),

('Kanyashree Prakalpa', 'Conditional Cash Transfers to improve status of girls from disadvantaged families, incentivizing education completion and preventing child marriage.', 'Education', 'West Bengal', 'Annual scholarship + one-time grant', ARRAY['School Certificate', 'Income Certificate', 'Bank Details'], 'https://www.myscheme.gov.in/schemes/wbkanyashree', '{"target_group": ["Girl Students"], "profession": ["Student"]}'::jsonb, 'Women and Child Development WB', NULL, NULL, 120000),

('Sabooj Sathi', 'Free bicycles to students in classes IX-XII studying in government and government-aided schools to improve access to education.', 'Education', 'West Bengal', 'Free bicycle', ARRAY['School Certificate', 'Identity Proof'], 'https://www.myscheme.gov.in/schemes/wbsaboojsathi', '{"target_group": ["Students"], "profession": ["Student"]}'::jsonb, 'Education Department West Bengal', NULL, NULL, NULL),

('Rupashree Prakalpa', 'One-time financial grant of ₹25,000/- to economically stressed families for their adult daughters marriages.', 'Social Security', 'West Bengal', '₹25,000/- one-time grant', ARRAY['Income Certificate', 'Age Proof', 'Marriage Certificate'], 'https://www.myscheme.gov.in/schemes/wbrupashree', '{"target_group": ["Poor Families"], "age_min": 18}'::jsonb, 'Social Welfare West Bengal', 18, NULL, 150000);

-- Maharashtra Schemes  
INSERT INTO schemes (name, description, category, state, benefits, required_documents, application_url, eligibility_criteria, department, age_min, age_max, income_max) VALUES
('Mahatma Jyotirao Phule Jan Arogya Yojana', 'Cashless treatment for identified diseases through network of government and private healthcare providers.', 'Healthcare', 'Maharashtra', 'Cashless treatment up to ₹1.5 lakhs', ARRAY['Identity Proof', 'Income Certificate', 'Residence Proof'], 'https://www.myscheme.gov.in/schemes/mjpjay', '{"target_group": ["BPL Families"]}'::jsonb, 'Health Department Maharashtra', NULL, NULL, 100000),

('Mukhyamantri Majhi Ladki Bahin Yojana', 'Monthly financial assistance for economic freedom of women aged 21-65, improving health and nutrition through DBT.', 'Women Empowerment', 'Maharashtra', 'Monthly financial assistance via DBT', ARRAY['Age Proof', 'Identity Proof', 'Bank Details'], 'https://www.myscheme.gov.in/schemes/mmlby', '{"target_group": ["Women"], "profession": ["Housewife", "Working Professional"]}'::jsonb, 'Women and Child Development Maharashtra', 21, 65, 250000),

('Namo Shetkari Mahasanman Nidhi Yojana', 'Additional ₹6,000/- per year to farmer families (supplementing PM-KISAN ₹6,000/-) to increase farmer income.', 'Agriculture', 'Maharashtra', '₹6,000/- per year additional', ARRAY['Land Records', 'PM-KISAN Registration', 'Bank Details'], 'https://www.myscheme.gov.in/schemes/namo-shetkari-mahasanman-nidhi-yojana', '{"target_group": ["Farmers"], "profession": ["Farmer"]}'::jsonb, 'Agriculture Department Maharashtra', NULL, NULL, NULL),

('Chief Minister Employment Generation Programme', 'Credit-linked subsidy for establishing Micro & Small Enterprises to generate employment in urban and rural areas.', 'Entrepreneurship', 'Maharashtra', 'Credit-linked subsidy for MSMEs', ARRAY['Project Report', 'Identity Proof', 'Caste Certificate'], 'https://www.myscheme.gov.in/schemes/cmegp', '{"target_group": ["SC", "ST", "OBC", "Women", "PwD"], "profession": ["Unemployed", "Self Employed", "Business Owner"]}'::jsonb, 'Industries Department Maharashtra', 18, NULL, NULL),

('Dr. Panjabrao Deshmukh Hostel Maintenance Allowance', 'Hostel allowance for students whose parents annual income is below ₹8 lakhs and are marginal landholders or registered laborers.', 'Education', 'Maharashtra', 'Hostel maintenance allowance', ARRAY['Income Certificate', 'College ID', 'Hostel Certificate'], 'https://www.myscheme.gov.in/schemes/drpdhma', '{"target_group": ["Students"], "profession": ["Student"]}'::jsonb, 'Education Department Maharashtra', NULL, NULL, 800000),

('Swami Vivekananda Merit-cum-Means Scholarship', 'Financial assistance to meritorious students from economically weaker sections for higher education.', 'Education', 'Maharashtra', 'Scholarship for higher education', ARRAY['Mark Sheets', 'Income Certificate', 'College ID'], 'https://www.myscheme.gov.in/schemes/svmcms', '{"target_group": ["Students"], "profession": ["Student"]}'::jsonb, 'Higher Education Maharashtra', NULL, NULL, 800000);