-- Add West Bengal schemes
INSERT INTO schemes (id, name, description, category, eligibility_criteria, benefits, required_documents, application_url, state, department) VALUES
(gen_random_uuid(), 'Banglar Awaas Yojana', 'Provides financial assistance to houseless households and those living in kutcha or dilapidated houses for building pucca houses.', 'Housing & Shelter', '{"target_group": ["General Public"], "special_conditions": ["Houseless or living in kutcha houses"]}'::jsonb, 'Financial assistance with additional support for toilets', ARRAY['Identity proof', 'Income certificate', 'Property documents'], 'https://www.myscheme.gov.in/schemes/bay', 'West Bengal', 'Housing Department'),

(gen_random_uuid(), 'Kanyashree Prakalpa', 'Improves status and wellbeing of girls through Conditional Cash Transfers to incentivize education completion.', 'Social welfare & Empowerment', '{"target_group": ["Girl Child", "Students"], "gender_specific": "Female", "special_conditions": ["From socio-economically disadvantaged families"]}'::jsonb, 'Cash transfers for education continuation', ARRAY['School certificate', 'Income certificate', 'Identity proof'], 'https://www.myscheme.gov.in/schemes/wbkanyashree', 'West Bengal', 'Women and Child Development'),

(gen_random_uuid(), 'Krishak Bandhu Scheme', 'Provides financial security to farmers through direct income support and death/disability benefits.', 'Agriculture,Rural & Environment', '{"target_group": ["Farmers"], "special_conditions": ["Small and marginal farmers"]}'::jsonb, 'Annual assistance of Rs 5,000 per acre and Rs 2,00,000 in case of death', ARRAY['Land documents', 'Identity proof', 'Bank account details'], 'https://www.myscheme.gov.in/schemes/kbs', 'West Bengal', 'Agriculture Department'),

(gen_random_uuid(), 'Lakshmir Bhandar Scheme', 'Provides financial assistance to women from economically weaker sections for empowerment.', 'Social welfare & Empowerment', '{"target_group": ["Women"], "gender_specific": "Female", "age_min": 25, "age_max": 60, "special_conditions": ["Enrolled in Swasthya Sathi"]}'::jsonb, 'Monthly financial assistance', ARRAY['Identity proof', 'Income certificate', 'Swasthya Sathi enrollment'], 'https://www.myscheme.gov.in/schemes/lbs-wb', 'West Bengal', 'Women and Child Development'),

(gen_random_uuid(), 'Sabooj Sathi', 'Provides bicycles free of cost to students studying in government and government-aided schools from classes IX to XII.', 'Social welfare & Empowerment', '{"target_group": ["Students"], "education_required": "Class IX to XII", "special_conditions": ["Government and aided schools"]}'::jsonb, 'Free bicycle distribution', ARRAY['School certificate', 'Identity proof'], 'https://www.myscheme.gov.in/schemes/wbsaboojsathi', 'West Bengal', 'Education Department'),

(gen_random_uuid(), 'Rupashree Prakalpa', 'Provides one-time financial grant to economically stressed families at the time of their adult daughters marriages.', 'Social welfare & Empowerment', '{"target_group": ["Women", "Poor Families"], "gender_specific": "Female", "special_conditions": ["Economically stressed families"]}'::jsonb, 'One-time grant of Rs 25,000', ARRAY['Income certificate', 'Marriage invitation', 'Identity proof'], 'https://www.myscheme.gov.in/schemes/wbrupashree', 'West Bengal', 'Women and Child Development'),

(gen_random_uuid(), 'Sishu Saathi', 'Treats Indian children of 0-18 years age group with zero out of pocket expenditure under RBSK.', 'Health & Wellness', '{"target_group": ["Children"], "age_min": 0, "age_max": 18, "special_conditions": ["Under Rastriya Bal Swasthya Karyakram"]}'::jsonb, 'Zero out of pocket medical treatment', ARRAY['Birth certificate', 'Identity proof', 'Medical documents'], 'https://www.myscheme.gov.in/schemes/wbsishusathi', 'West Bengal', 'Health and Family Welfare'),

(gen_random_uuid(), 'Swami Vivekananda Merit cum Means Scholarship', 'Provides financial assistance to students for higher education.', 'Education & Learning', '{"target_group": ["Students"], "education_required": "Higher Education", "special_conditions": ["Merit cum means based"]}'::jsonb, 'Scholarship for higher education', ARRAY['Academic certificates', 'Income certificate', 'Admission letter'], 'https://www.myscheme.gov.in/schemes/svmcms', 'West Bengal', 'Higher Education Department'),

(gen_random_uuid(), 'Yuvasree Prakalpa', 'Provides financial assistance to jobseekers for employment and placement.', 'Skills & Employment', '{"target_group": ["Youth", "Job Seekers"], "special_conditions": ["For employment assistance"]}'::jsonb, 'Financial assistance for job placement', ARRAY['Identity proof', 'Educational certificates', 'Employment registration'], 'https://www.myscheme.gov.in/schemes/yuvasree', 'West Bengal', 'Labour Department'),

(gen_random_uuid(), 'Karma Sathi Prakalpa', 'Helps young entrepreneurs establish new manufacturing enterprises and small businesses with soft loans and subsidies.', 'Skills & Employment', '{"target_group": ["Youth", "Entrepreneurs"], "special_conditions": ["For new income-generating projects"]}'::jsonb, 'Soft loans and subsidies', ARRAY['Business plan', 'Identity proof', 'Educational certificates'], 'https://www.myscheme.gov.in/schemes/ksp', 'West Bengal', 'MSME Department'),

-- Add Maharashtra schemes
(gen_random_uuid(), 'Mahatma Jyotirao Phule Jan Arogya Yojana', 'Offers cashless treatment for identified diseases through network of government and private healthcare providers.', 'Health & Wellness', '{"target_group": ["General Public"], "special_conditions": ["For identified diseases"]}'::jsonb, 'Cashless treatment for diseases', ARRAY['Identity proof', 'Income certificate', 'Medical documents'], 'https://www.myscheme.gov.in/schemes/mjpjay', 'Maharashtra', 'Health Department'),

(gen_random_uuid(), 'Mukhyamantri Majhi Ladki Bahin Yojana', 'Provides financial benefit to women for economic freedom, health and nutrition.', 'Social welfare & Empowerment', '{"target_group": ["Women"], "gender_specific": "Female", "age_min": 21, "age_max": 65, "special_conditions": ["For economic empowerment"]}'::jsonb, 'Monthly financial benefit through DBT', ARRAY['Identity proof', 'Income certificate', 'Bank account details'], 'https://www.myscheme.gov.in/schemes/mmlby', 'Maharashtra', 'Women and Child Development'),

(gen_random_uuid(), 'Namo Shetkari Mahasanman Nidhi Yojana', 'Provides additional amount of Rs 6000 per year to cultivable land holding farmer families along with PM KISAN.', 'Agriculture,Rural & Environment', '{"target_group": ["Farmers"], "special_conditions": ["Cultivable land holding families"]}'::jsonb, 'Rs 6000 per year additional to PM KISAN', ARRAY['Land documents', 'Identity proof', 'Bank account details'], 'https://www.myscheme.gov.in/schemes/namo-shetkari-mahasanman-nidhi-yojana', 'Maharashtra', 'Agriculture Department'),

(gen_random_uuid(), 'Chief Minister Employment Generation Programme', 'Generates employment opportunities through establishment of Micro and Small Enterprises in rural and urban areas.', 'Business & Entrepreneurship', '{"target_group": ["Scheduled Caste", "Scheduled Tribe", "OBC", "Women", "PwD"], "special_conditions": ["For micro and small enterprises"]}'::jsonb, 'Credit linked subsidy for enterprises', ARRAY['Business plan', 'Identity proof', 'Caste certificate if applicable'], 'https://www.myscheme.gov.in/schemes/cmegp', 'Maharashtra', 'Industries Department'),

(gen_random_uuid(), 'Mukhyamantri Yuva Karya Prashikshan Yojana', 'Enhances candidates employability through practical training with entrepreneurs.', 'Skills & Employment', '{"target_group": ["Youth", "Students"], "special_conditions": ["For vocational training"]}'::jsonb, 'Practical training with stipend', ARRAY['Educational certificates', 'Identity proof', 'Application form'], 'https://www.myscheme.gov.in/schemes/mmykpy', 'Maharashtra', 'Skill Development Department'),

(gen_random_uuid(), 'Rajarshri Chhatrapati Shahu Maharaj Merit Scholarship', 'Encourages scheduled caste students to pursue higher secondary education.', 'Education & Learning', '{"target_group": ["Scheduled Caste", "Students"], "education_required": "Higher Secondary", "special_conditions": ["Merit-based for SC students"]}'::jsonb, 'Merit scholarship for higher secondary', ARRAY['Caste certificate', 'Academic certificates', 'School certificate'], 'https://www.myscheme.gov.in/schemes/rcsmms', 'Maharashtra', 'Social Justice Department'),

(gen_random_uuid(), 'Ramai Awas Gharkul Scheme', 'Raises standard of living of Scheduled Caste and Nav-Buddha communities through housing assistance.', 'Housing & Shelter', '{"target_group": ["Scheduled Caste"], "special_conditions": ["For SC and Nav-Buddha communities"]}'::jsonb, 'Housing assistance', ARRAY['Caste certificate', 'Income certificate', 'Property documents'], 'https://www.myscheme.gov.in/schemes/rassnb', 'Maharashtra', 'Social Justice Department'),

(gen_random_uuid(), 'Sanjay Gandhi Niradhar Grant Scheme', 'Provides monthly financial assistance to destitute persons including widows, transgender, PwD, and orphans.', 'Social welfare & Empowerment', '{"target_group": ["Widows", "Transgender", "PwD", "Orphans"], "special_conditions": ["Below Poverty Line", "Destitute persons"]}'::jsonb, 'Rs 600 to Rs 900 per month', ARRAY['Identity proof', 'Income certificate', 'BPL card'], 'https://www.myscheme.gov.in/schemes/sgngs', 'Maharashtra', 'Social Justice Department'),

(gen_random_uuid(), 'Indira Gandhi National Old Age Pension Maharashtra', 'Provides monthly pension to elderly individuals aged 65 years and above from BPL families.', 'Social welfare & Empowerment', '{"target_group": ["Senior Citizens"], "age_min": 65, "special_conditions": ["BPL families"]}'::jsonb, 'Rs 600 per month pension', ARRAY['Age proof', 'BPL card', 'Identity proof'], 'https://www.myscheme.gov.in/schemes/igoapsm', 'Maharashtra', 'Social Justice Department'),

(gen_random_uuid(), 'Indira Gandhi National Widow Pension Maharashtra', 'Provides pension to widows aged 40 to 79 years from BPL families.', 'Social welfare & Empowerment', '{"target_group": ["Widows", "Women"], "gender_specific": "Female", "age_min": 40, "age_max": 79, "special_conditions": ["BPL families"]}'::jsonb, 'Rs 1500 per month pension', ARRAY['Widow certificate', 'Age proof', 'BPL card', 'Identity proof'], 'https://www.myscheme.gov.in/schemes/ignwpsm', 'Maharashtra', 'Social Justice Department');
