-- Migration: Add Batch 4 schemes (16 West Bengal + 12 Maharashtra schemes)
-- Total schemes after this batch: ~172
-- Fixed: Proper JSONB and ARRAY formatting

INSERT INTO schemes (
  id,
  name,
  description,
  category,
  eligibility_criteria,
  benefits,
  required_documents,
  application_url,
  deadline,
  state,
  department,
  age_min,
  age_max,
  income_max,
  gender_specific,
  education_required
) VALUES

-- West Bengal Schemes (16 schemes)
(
  gen_random_uuid(),
  'Accidental Benefit',
  'The "Accidental Benefit" scheme by the BOCW Welfare Board, Labour Department, West Bengal, is a welfare scheme that provides financial assistance to the beneficiary in case of hospitalization and disability due to an accident.',
  'Social welfare & Empowerment',
  '{"description": "Registered construction workers in West Bengal who have suffered accidents resulting in hospitalization or disability"}'::jsonb,
  'Financial assistance for hospitalization and disability due to accidents',
  ARRAY['Registration certificate', 'Accident report', 'Medical certificates', 'Hospitalization bills'],
  'https://www.myscheme.gov.in/schemes/adwb',
  NULL,
  'West Bengal',
  'Labour Department',
  18,
  60,
  NULL,
  NULL,
  NULL
),

(
  gen_random_uuid(),
  'Akanksha Housing Scheme',
  'Akanksha Housing Scheme was launched by the Housing Department, Government of West Bengal on 28/02/2014 to provide housing to the serving State Government employees.',
  'Housing & Shelter',
  '{"description": "Serving State Government employees of West Bengal"}'::jsonb,
  'Housing assistance for government employees',
  ARRAY['Employment certificate', 'Identity proof', 'Income certificate', 'Residence proof'],
  'https://www.myscheme.gov.in/schemes/ahs',
  NULL,
  'West Bengal',
  'Housing Department',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
),

(
  gen_random_uuid(),
  'Banglar Awaas Yojana (BAY)',
  '"Banglar Awaas Yojana (BAY)" provides financial assistance to houseless households and those living in kutcha or dilapidated houses, helping them build pucca houses with essential amenities.',
  'Housing & Shelter',
  '{"description": "Houseless households and those living in kutcha or dilapidated houses in West Bengal"}'::jsonb,
  'Financial assistance for building pucca houses with essential amenities including toilets',
  ARRAY['Identity proof', 'Residence proof', 'Income certificate', 'House ownership documents'],
  'https://www.myscheme.gov.in/schemes/bay',
  NULL,
  'West Bengal',
  'Housing Department',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
),

(
  gen_random_uuid(),
  'Death Benefit',
  'The "Death Benefit" scheme by the BOCW Welfare Board, Labour Department, West Bengal, is a welfare scheme that provides financial assistance to the nominee(s) of the beneficiary as death benefit.',
  'Social welfare & Empowerment',
  '{"description": "Nominees of registered construction workers in West Bengal who have passed away"}'::jsonb,
  'Financial assistance to nominees in case of death of registered worker',
  ARRAY['Death certificate', 'Registration certificate', 'Nominee identification', 'Bank account details'],
  'https://www.myscheme.gov.in/schemes/dbftcwwb',
  NULL,
  'West Bengal',
  'Labour Department',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
),

(
  gen_random_uuid(),
  'Disability Pension - West Bengal',
  'In 2010, the Women and Child Development and Social Welfare Department of the West Bengal State Government introduced the "Disability Pension" scheme.',
  'Social welfare & Empowerment',
  '{"description": "Persons with disabilities in West Bengal meeting specified disability percentage criteria"}'::jsonb,
  'Monthly pension for persons with disabilities',
  ARRAY['Disability certificate', 'Identity proof', 'Income certificate', 'Bank account details'],
  'https://www.myscheme.gov.in/schemes/dpwb',
  NULL,
  'West Bengal',
  'Women and Child Development and Social Welfare Department',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
),

(
  gen_random_uuid(),
  'Financial Assistance for Education of Self/Children of Beneficiaries',
  'The "Financial Assistance for Education of Self/Children of Beneficiaries" scheme by the BOCW Welfare Board, Labour Department, West Bengal, provides financial assistance to registered members or their children studying Higher Secondary and above.',
  'Education & Learning',
  '{"description": "Registered construction workers or their children studying Higher Secondary and above in West Bengal"}'::jsonb,
  'Financial assistance for education expenses',
  ARRAY['Registration certificate', 'Educational certificates', 'Admission proof', 'Bank account details'],
  'https://www.myscheme.gov.in/schemes/fafeoscob',
  NULL,
  'West Bengal',
  'Labour Department',
  NULL,
  NULL,
  NULL,
  NULL,
  'Higher Secondary'
),

(
  gen_random_uuid(),
  'Funeral Expenses for the Construction Workers',
  'The "Funeral Expenses for the Construction Workers" scheme by the BOCW Welfare Board, Labour Department, West Bengal, provides financial assistance for funeral expenses to the nominees of a deceased registered member.',
  'Social welfare & Empowerment',
  '{"description": "Nominees of deceased registered construction workers in West Bengal"}'::jsonb,
  'Financial assistance for funeral expenses',
  ARRAY['Death certificate', 'Registration certificate', 'Nominee identification', 'Funeral expense receipts'],
  'https://www.myscheme.gov.in/schemes/feftcwwb',
  NULL,
  'West Bengal',
  'Labour Department',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
),

(
  gen_random_uuid(),
  'Gatidhara Scheme',
  'The scheme "Gatidhara Scheme" was launched by the Transport Department, Government of West Bengal in August 2014 for employment of registered unemployed youth of the State in the transport sector.',
  'Business & Entrepreneurship',
  '{"description": "Registered unemployed youth of West Bengal seeking employment in transport sector"}'::jsonb,
  'Subsidy for purchasing commercial vehicles for transport services',
  ARRAY['Unemployment registration', 'Identity proof', 'Residence proof', 'Driving license'],
  'https://www.myscheme.gov.in/schemes/gs-west-bengal',
  NULL,
  'West Bengal',
  'Transport Department',
  18,
  45,
  NULL,
  NULL,
  NULL
),

(
  gen_random_uuid(),
  'Kanyashree Prakalpa',
  'The scheme to improve the status and wellbeing of girls, specifically those from socio-economically disadvantaged families, through Conditional Cash Transfers by incentivising them to continue in education.',
  'Education & Learning',
  '{"description": "Girls from socio-economically disadvantaged families in West Bengal continuing their education"}'::jsonb,
  'Conditional cash transfers to encourage education and prevent child marriage',
  ARRAY['School enrollment certificate', 'Identity proof', 'Income certificate', 'Bank account details'],
  'https://www.myscheme.gov.in/schemes/wbkanyashree',
  NULL,
  'West Bengal',
  'Women and Child Development Department',
  13,
  18,
  120000,
  'Female',
  NULL
),

(
  gen_random_uuid(),
  'Krishak Bandhu Scheme',
  'The scheme aims to provide financial security to farmers through direct income support and death/disability benefits. It benefits small and marginal farmers with annual assistance.',
  'Agriculture,Rural & Environment',
  '{"description": "Small and marginal farmers in West Bengal"}'::jsonb,
  'Annual assistance of ₹5,000/- per acre and one-time payout of ₹2,00,000/- in case of death',
  ARRAY['Land ownership documents', 'Identity proof', 'Bank account details', 'Residence proof'],
  'https://www.myscheme.gov.in/schemes/kbs',
  NULL,
  'West Bengal',
  'Agriculture Department',
  18,
  60,
  NULL,
  NULL,
  NULL
),

(
  gen_random_uuid(),
  'Lakshmir Bhandar Scheme',
  'The "Lakshmir Bhandar" scheme is a flagship program to provide financial assistance to women from economically weaker sections of society, for the empowerment of women in the age group of 25-60 years.',
  'Social welfare & Empowerment',
  '{"description": "Women aged 25-60 years from economically weaker sections enrolled in Swasthya Sathi in West Bengal"}'::jsonb,
  'Monthly financial assistance for women empowerment',
  ARRAY['Identity proof', 'Age proof', 'Income certificate', 'Swasthya Sathi enrollment', 'Bank account details'],
  'https://www.myscheme.gov.in/schemes/lbs-wb',
  NULL,
  'West Bengal',
  'Women and Child Development Department',
  25,
  60,
  NULL,
  'Female',
  NULL
),

(
  gen_random_uuid(),
  'Maternity Benefit',
  'The "Maternity Benefit" scheme by the BOCW Welfare Board, Labour Department, West Bengal, provides maternity benefits up to two times in a lifetime to eligible female beneficiaries or wives of male beneficiaries.',
  'Health & Wellness',
  '{"description": "Female registered construction workers or wives of male registered workers in West Bengal"}'::jsonb,
  'Maternity benefits up to two times in lifetime',
  ARRAY['Registration certificate', 'Pregnancy certificate', 'Hospital delivery certificate', 'Bank account details'],
  'https://www.myscheme.gov.in/schemes/mbwb',
  NULL,
  'West Bengal',
  'Labour Department',
  18,
  45,
  NULL,
  'Female',
  NULL
),

(
  gen_random_uuid(),
  'Old Age Pension',
  'In 2010, the Women and Child Development and Social Welfare Department of the West Bengal State Government introduced the "Old Age Pension" scheme.',
  'Social welfare & Empowerment',
  '{"description": "Senior citizens aged 60 years and above in West Bengal meeting income criteria"}'::jsonb,
  'Monthly pension for senior citizens',
  ARRAY['Age proof', 'Identity proof', 'Income certificate', 'Bank account details'],
  'https://www.myscheme.gov.in/schemes/oapwb',
  NULL,
  'West Bengal',
  'Women and Child Development and Social Welfare Department',
  60,
  NULL,
  NULL,
  NULL,
  NULL
),

(
  gen_random_uuid(),
  'Pension Benefit',
  'The "Pension Benefit" scheme by the BOCW Welfare Board, Labour Department, West Bengal, provides a monthly pension after completion of 60 years to the eligible registered member.',
  'Social welfare & Empowerment',
  '{"description": "Registered construction workers in West Bengal aged 60 years and above"}'::jsonb,
  'Monthly pension after age 60',
  ARRAY['Registration certificate', 'Age proof', 'Identity proof', 'Bank account details'],
  'https://www.myscheme.gov.in/schemes/pbwb',
  NULL,
  'West Bengal',
  'Labour Department',
  60,
  NULL,
  NULL,
  NULL,
  NULL
),

(
  gen_random_uuid(),
  'Rupashree Prakalpa',
  'The scheme aims to mitigate the financial difficulties faced by poor families in bearing the expenses of their daughters marriages. A one-time financial grant of ₹25,000/- is provided.',
  'Social welfare & Empowerment',
  '{"description": "Economically stressed families in West Bengal with adult daughters getting married"}'::jsonb,
  'One-time financial grant of ₹25,000/- for daughter marriage',
  ARRAY['Identity proof', 'Income certificate', 'Marriage invitation', 'Bank account details'],
  'https://www.myscheme.gov.in/schemes/wbrupashree',
  NULL,
  'West Bengal',
  'Women and Child Development Department',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
),

(
  gen_random_uuid(),
  'Widow Pension - West Bengal',
  'The West Bengal governments Women and Child Development and Social Welfare Department launched the "Widow Pension" scheme in 2010 to support widows facing economic hardship.',
  'Social welfare & Empowerment',
  '{"description": "Widows facing economic hardship in West Bengal"}'::jsonb,
  'Monthly pension for widows',
  ARRAY['Death certificate of spouse', 'Identity proof', 'Income certificate', 'Bank account details'],
  'https://www.myscheme.gov.in/schemes/wpwb',
  NULL,
  'West Bengal',
  'Women and Child Development and Social Welfare Department',
  NULL,
  NULL,
  NULL,
  'Female',
  NULL
),

-- Maharashtra Schemes (12 schemes)
(
  gen_random_uuid(),
  'Chief Minister Employment Generation Programme (CMEGP)',
  'Government of Maharashtra has approved the introduction of a new credit linked subsidy program for generation of employment opportunities through establishment of Micro & Small Enterprises in rural as well as urban areas.',
  'Business & Entrepreneurship',
  '{"description": "Entrepreneurs from SC, ST, OBC, Female, PwD, and VJNT categories in Maharashtra"}'::jsonb,
  'Credit linked subsidy for establishing micro and small enterprises',
  ARRAY['Identity proof', 'Caste certificate', 'Project report', 'Bank account details'],
  'https://www.myscheme.gov.in/schemes/cmegp',
  '2024-07-31',
  'Maharashtra',
  'Industries Department',
  18,
  NULL,
  NULL,
  NULL,
  NULL
),

(
  gen_random_uuid(),
  'Dr. Panjabrao Deshmukh Hostel Maintenance Allowance',
  'This scheme is for students whose parents annual income is below 800000 and students whose parents are marginal land holders and registered laborers.',
  'Education & Learning',
  '{"description": "Students in Maharashtra whose parents annual income is below ₹8,00,000 or are marginal land holders/registered laborers"}'::jsonb,
  'Hostel maintenance allowance for eligible students',
  ARRAY['Income certificate', 'Educational certificates', 'Hostel admission proof', 'Bank account details'],
  'https://www.myscheme.gov.in/schemes/drpdhma',
  NULL,
  'Maharashtra',
  'Education Department',
  NULL,
  NULL,
  800000,
  NULL,
  NULL
),

(
  gen_random_uuid(),
  'Educational Assistance for Degree Course',
  'The Educational Assistance for Degree Course scheme provides financial assistance to children of registered construction workers pursuing their undergraduate degree.',
  'Education & Learning',
  '{"description": "Children of registered construction workers in Maharashtra pursuing undergraduate degrees"}'::jsonb,
  'Financial assistance for degree course education',
  ARRAY['Registration certificate', 'Admission proof', 'Educational certificates', 'Bank account details'],
  'https://www.myscheme.gov.in/schemes/eafdc',
  NULL,
  'Maharashtra',
  'Labour Department',
  NULL,
  NULL,
  NULL,
  NULL,
  'Undergraduate'
),

(
  gen_random_uuid(),
  'Financial Assistance for Girl Child Attend Her Age of 18',
  'The scheme provides financial assistance in the form of a fixed deposit of ₹1,00,000/- for each female child of a registered worker or spouse who has undergone family planning operation.',
  'Social welfare & Empowerment',
  '{"description": "Female children of registered construction workers in Maharashtra who turn 18 years"}'::jsonb,
  'Fixed deposit of ₹1,00,000/- for girl child at age 18',
  ARRAY['Registration certificate', 'Birth certificate', 'Family planning certificate', 'Bank account details'],
  'https://www.myscheme.gov.in/schemes/fagcaha18',
  NULL,
  'Maharashtra',
  'Labour Department',
  18,
  18,
  NULL,
  'Female',
  NULL
),

(
  gen_random_uuid(),
  'Financial Assistance for Natural Death',
  'The scheme provides financial assistance of ₹2,00,000/- to the legal heir of a registered worker who dies naturally.',
  'Social welfare & Empowerment',
  '{"description": "Legal heirs of registered construction workers in Maharashtra who died naturally"}'::jsonb,
  'Financial assistance of ₹2,00,000/- for natural death',
  ARRAY['Death certificate', 'Registration certificate', 'Legal heir certificate', 'Bank account details'],
  'https://www.myscheme.gov.in/schemes/fafnd',
  NULL,
  'Maharashtra',
  'Labour Department',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
),

(
  gen_random_uuid(),
  'Indira Gandhi National Old Age Pension Scheme (Maharashtra)',
  'The scheme provides ₹600 per month to elderly individuals aged 65 years and above from BPL families.',
  'Social welfare & Empowerment',
  '{"description": "Elderly individuals aged 65 years and above from BPL families in Maharashtra"}'::jsonb,
  'Monthly pension of ₹600 for senior citizens',
  ARRAY['Age proof', 'BPL card', 'Identity proof', 'Bank account details'],
  'https://www.myscheme.gov.in/schemes/igoapsm',
  NULL,
  'Maharashtra',
  'Social Justice and Special Assistance Department',
  65,
  NULL,
  NULL,
  NULL,
  NULL
),

(
  gen_random_uuid(),
  'Indira Gandhi National Widow Pension Scheme (Maharashtra)',
  'Widows aged 40 to 79 years who are from a BPL family receive a pension of ₹1500/- per month.',
  'Social welfare & Empowerment',
  '{"description": "Widows aged 40-79 years from BPL families in Maharashtra"}'::jsonb,
  'Monthly pension of ₹1500 for widows',
  ARRAY['Death certificate of spouse', 'Age proof', 'BPL card', 'Identity proof', 'Bank account details'],
  'https://www.myscheme.gov.in/schemes/ignwpsm',
  NULL,
  'Maharashtra',
  'Social Justice and Special Assistance Department',
  40,
  79,
  NULL,
  'Female',
  NULL
),

(
  gen_random_uuid(),
  'Mahatma Jyotirao Phule Jan Arogya Yojana',
  'The scheme offers cashless treatment for identified diseases through a network of government and private healthcare providers.',
  'Health & Wellness',
  '{"description": "Families in Maharashtra eligible for health insurance coverage"}'::jsonb,
  'Cashless treatment for identified diseases',
  ARRAY['Identity proof', 'Income certificate', 'Residence proof', 'Health card'],
  'https://www.myscheme.gov.in/schemes/mjpjay',
  NULL,
  'Maharashtra',
  'Health Department',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
),

(
  gen_random_uuid(),
  'Mukhyamantri - Majhi Ladki Bahin Yojana',
  'The scheme is for the economic freedom of women in the state age group of 21 to 65, improving their health and nutrition and strengthening their decisive role in the family.',
  'Social welfare & Empowerment',
  '{"description": "Women aged 21-65 years in Maharashtra from economically weaker sections"}'::jsonb,
  'Monthly financial assistance through direct benefit transfer',
  ARRAY['Identity proof', 'Age proof', 'Income certificate', 'Bank account details'],
  'https://www.myscheme.gov.in/schemes/mmlby',
  NULL,
  'Maharashtra',
  'Women and Child Development Department',
  21,
  65,
  NULL,
  'Female',
  NULL
),

(
  gen_random_uuid(),
  'Mukhyamantri Yuva Karya Prashikshan Yojana',
  'The scheme enhances candidates employability through practical training with entrepreneurs with a budget of ₹5,500 crore.',
  'Skills & Employment',
  '{"description": "Youth in Maharashtra seeking vocational training and employment"}'::jsonb,
  'Practical training with stipend for employability enhancement',
  ARRAY['Identity proof', 'Educational certificates', 'Bank account details'],
  'https://www.myscheme.gov.in/schemes/mmykpy',
  NULL,
  'Maharashtra',
  'Skill Development Department',
  18,
  35,
  NULL,
  NULL,
  NULL
),

(
  gen_random_uuid(),
  'National Family Benefit Scheme (Maharashtra)',
  'Under this scheme, ₹20,000/- is provided to the family in the event of the death of their primary breadwinner.',
  'Social welfare & Empowerment',
  '{"description": "BPL families in Maharashtra who have lost their primary breadwinner"}'::jsonb,
  'One-time assistance of ₹20,000/- on death of primary breadwinner',
  ARRAY['Death certificate', 'BPL card', 'Identity proof', 'Bank account details'],
  'https://www.myscheme.gov.in/schemes/nfbsm',
  NULL,
  'Maharashtra',
  'Social Justice and Special Assistance Department',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
),

(
  gen_random_uuid(),
  'Shravanbal Seva State Pension Scheme',
  'A monthly pension of ₹600/- is provided to destitute persons in the state of Maharashtra.',
  'Social welfare & Empowerment',
  '{"description": "Destitute persons and senior citizens in Maharashtra"}'::jsonb,
  'Monthly pension of ₹600 for destitute persons',
  ARRAY['Age proof', 'Identity proof', 'Income certificate', 'Bank account details'],
  'https://www.myscheme.gov.in/schemes/sbssps',
  NULL,
  'Maharashtra',
  'Social Justice and Special Assistance Department',
  60,
  NULL,
  NULL,
  NULL,
  NULL
);
