-- Add Delhi schemes batch 1 (20 schemes)
INSERT INTO schemes (id, name, description, category, eligibility_criteria, benefits, required_documents, application_url, state, department) VALUES
(gen_random_uuid(), 'Accidental Death Assistance for the Construction Workers', 'Welfare scheme that provides financial assistance of Rs 2,00,000 to the nominees/dependents of the members in case the death is due to an accident.', 'Social welfare & Empowerment', '{"target_group": ["Construction Workers", "Labour"], "special_conditions": ["Registered with Delhi Building and Other Construction Workers Welfare Board"]}'::jsonb, 'Rs 2,00,000 financial assistance', ARRAY['Registration certificate', 'Death certificate', 'Accident report'], 'https://www.myscheme.gov.in/schemes/adacw', 'Delhi', 'Labour Department'),

(gen_random_uuid(), 'Artisan Promotion', 'Provides artisans with opportunities to participate in national fairs and exhibitions with financial support for participation fees, lodging, boarding, and stipends.', 'Business & Entrepreneurship', '{"target_group": ["Artisans", "Scheduled Caste", "OBC", "Minorities"], "special_conditions": ["Active artisan practicing traditional crafts"]}'::jsonb, 'Financial support for participation fees, lodging, boarding, and stipends', ARRAY['Artisan registration', 'Caste certificate', 'Identity proof'], 'https://www.myscheme.gov.in/schemes/ap', 'Delhi', 'DSFDC'),

(gen_random_uuid(), 'Big Loan Scheme', 'Provides term loans up to Rs 5,00,000 for income-generating activities to eligible applicants from SC, OBC, Minorities, Safai Karamcharis, and PwDs.', 'Business & Entrepreneurship', '{"target_group": ["Scheduled Caste", "OBC", "Minorities", "Safai Karamcharis", "PwD"], "special_conditions": ["For income-generating activities"]}'::jsonb, 'Term loans up to Rs 5,00,000', ARRAY['Caste certificate', 'Income certificate', 'Business plan', 'Identity proof'], 'https://www.myscheme.gov.in/schemes/bls', 'Delhi', 'DSFDC'),

(gen_random_uuid(), 'Bus Traveling Facility For Visually Impaired', 'Delhi Transport Corporation provides facility of free traveling in DTC Buses to the persons with vision impairment.', 'Social welfare & Empowerment', '{"target_group": ["Visually Impaired", "PwD"], "special_conditions": ["Vision impairment certificate required"]}'::jsonb, 'Free bus traveling in DTC Buses', ARRAY['Disability certificate', 'Identity proof'], 'https://www.myscheme.gov.in/schemes/btfvibc', 'Delhi', 'Social Welfare Department'),

(gen_random_uuid(), 'Composite Loan Scheme', 'Provides need-based financial support to individuals from SC, ST, OBC, Minorities, and PwDs for income-generating activities.', 'Business & Entrepreneurship', '{"target_group": ["Scheduled Caste", "Scheduled Tribe", "OBC", "Minorities", "PwD"], "special_conditions": ["For self-employment and entrepreneurship"]}'::jsonb, 'Financial support for income-generating activities', ARRAY['Caste certificate', 'Income certificate', 'Business plan'], 'https://www.myscheme.gov.in/schemes/cls', 'Delhi', 'DSFDC'),

(gen_random_uuid(), 'Delhi Arogya Kosh', 'Provides financial assistance to needy eligible patients for treatment of any illness in Government Hospitals run by Delhi Government or Central Government.', 'Health & Wellness', '{"target_group": ["General Public"], "special_conditions": ["Treatment in Government Hospital", "Needy patients"]}'::jsonb, 'Financial assistance for medical treatment', ARRAY['Income certificate', 'Medical documents', 'Hospital admission proof'], 'https://www.myscheme.gov.in/schemes/dak', 'Delhi', 'Health Department'),

(gen_random_uuid(), 'Delhi Arogya Nidhi', 'Provides financial assistance upto Rs 1.5 lacs to needy patients who have National Food Security Cards for treatment in Government hospitals only.', 'Health & Wellness', '{"target_group": ["National Food Security Card Holders"], "income_max": 100000, "special_conditions": ["Treatment in Government hospitals only"]}'::jsonb, 'Financial assistance up to Rs 1.5 lacs', ARRAY['National Food Security Card', 'Medical documents', 'Hospital admission proof'], 'https://www.myscheme.gov.in/schemes/dan', 'Delhi', 'Health Department'),

(gen_random_uuid(), 'Delhi Pension Scheme To Women In Distress', 'Provides social security by way of financial assistance to widows, divorced, separated, abandoned, deserted or destitute women aged 18 years and above.', 'Social welfare & Empowerment', '{"target_group": ["Women", "Widows", "Divorced", "Separated"], "age_min": 18, "special_conditions": ["Women in distress without adequate means of subsistence"]}'::jsonb, 'Monthly pension for women in distress', ARRAY['Identity proof', 'Income certificate', 'Widow or divorce certificate'], 'https://www.myscheme.gov.in/schemes/dpswdwp', 'Delhi', 'Social Welfare Department'),

(gen_random_uuid(), 'Dilli Swarojgar Yojna', 'Provides loans up to Rs 5,00,000 at 6 percent interest for income-generating activities for SC, ST, OBC, and Minority communities.', 'Business & Entrepreneurship', '{"target_group": ["Scheduled Caste", "Scheduled Tribe", "OBC", "Minorities"], "special_conditions": ["For income-generating activities like shops, dairy, tailoring"]}'::jsonb, 'Loans up to Rs 5,00,000 at 6 percent interest', ARRAY['Caste certificate', 'Income certificate', 'Business plan', 'Identity proof'], 'https://www.myscheme.gov.in/schemes/dsy', 'Delhi', 'DSFDC'),

(gen_random_uuid(), 'Disability Pension for the Construction Workers', 'Provides monthly disability pension of Rs 3000 to permanently disabled construction workers due to paralysis, leprosy, TB and accidents.', 'Social welfare & Empowerment', '{"target_group": ["Construction Workers", "PwD"], "special_conditions": ["Permanently disabled due to paralysis, leprosy, TB or accidents", "Registered with Board"]}'::jsonb, 'Monthly pension of Rs 3000', ARRAY['Disability certificate', 'Registration certificate', 'Medical documents'], 'https://www.myscheme.gov.in/schemes/dpcw', 'Delhi', 'Labour Department'),

(gen_random_uuid(), 'Dr. B. R. Ambedkar State Award', 'Recognizes and rewards meritorious SC/ST/OBC/Minority students pursuing graduation in recognised institutions.', 'Social welfare & Empowerment', '{"target_group": ["Scheduled Caste", "Scheduled Tribe", "OBC", "Minorities", "Students"], "education_required": "Graduation", "special_conditions": ["Meritorious students"]}'::jsonb, 'State award and financial assistance', ARRAY['Caste certificate', 'Academic certificates', 'Identity proof'], 'https://www.myscheme.gov.in/schemes/dbrasa', 'Delhi', 'Social Welfare Department'),

(gen_random_uuid(), 'Education Assistance for Construction Workers', 'Provides scholarship to the children of construction workers studying from school to graduation level.', 'Education & Learning', '{"target_group": ["Construction Workers", "Students"], "special_conditions": ["Children of registered construction workers"]}'::jsonb, 'Scholarship for education from school to graduation', ARRAY['Registration certificate', 'School or college admission proof', 'Academic certificates'], 'https://www.myscheme.gov.in/schemes/edftcw', 'Delhi', 'Labour Department'),

(gen_random_uuid(), 'Education Loan Scheme Delhi', 'Provides financial assistance to SC/ST/OBC/PwD students for pursuing professional and technical education in India and abroad.', 'Education & Learning', '{"target_group": ["Scheduled Caste", "Scheduled Tribe", "OBC", "PwD", "Students"], "income_max": 500000, "special_conditions": ["For professional and technical education"]}'::jsonb, 'Loan limits of Rs 7,50,000 for India and Rs 15,00,000 for abroad', ARRAY['Caste certificate', 'Income certificate', 'Admission letter', 'Academic certificates'], 'https://www.myscheme.gov.in/schemes/els-delhi', 'Delhi', 'Social Welfare Department'),

(gen_random_uuid(), 'Ex-gratia Payment for Construction Workers', 'Provides ex-gratia amount of Rs 1,00,000 in case of permanent disability of registered construction workers.', 'Social welfare & Empowerment', '{"target_group": ["Construction Workers", "PwD"], "special_conditions": ["Permanent disability", "Registered with Board"]}'::jsonb, 'Ex-gratia payment of Rs 1,00,000', ARRAY['Disability certificate', 'Registration certificate', 'Medical documents'], 'https://www.myscheme.gov.in/schemes/epcw', 'Delhi', 'Labour Department'),

(gen_random_uuid(), 'Family Pension DBOCWWB', 'Upon death of the pensioner, the surviving spouse is provided 50 percent of the pension amount or Rs 1500, whichever is higher.', 'Social welfare & Empowerment', '{"target_group": ["Construction Workers", "Family"], "special_conditions": ["Surviving spouse of deceased pensioner"]}'::jsonb, '50 percent of pension or Rs 1500 whichever is higher', ARRAY['Death certificate', 'Marriage certificate', 'Pension documents'], 'https://www.myscheme.gov.in/schemes/fpdbocwwb', 'Delhi', 'Labour Department'),

(gen_random_uuid(), 'Financial Assistance for Marriage', 'Provides financial assistance for marriage of self and for up to 2 children of registered construction workers.', 'Social welfare & Empowerment', '{"target_group": ["Construction Workers"], "special_conditions": ["For marriage of self or up to 2 children", "Registered with Board"]}'::jsonb, 'Financial assistance for marriage', ARRAY['Registration certificate', 'Marriage invitation', 'Identity proof'], 'https://www.myscheme.gov.in/schemes/famtw', 'Delhi', 'Labour Department'),

(gen_random_uuid(), 'Financial Assistance for Miscarriage', 'Provides Rs 3,000 as financial assistance in case of miscarriage to female construction workers.', 'Health & Wellness', '{"target_group": ["Construction Workers", "Women"], "gender_specific": "Female", "special_conditions": ["In case of miscarriage", "Registered with Board"]}'::jsonb, 'Rs 3,000 financial assistance', ARRAY['Registration certificate', 'Medical certificate'], 'https://www.myscheme.gov.in/schemes/famcw', 'Delhi', 'Labour Department'),

(gen_random_uuid(), 'Financial Assistance For Purchase Of Stationery', 'Provides help for purchase of stationery to SC/ST/OBC/Minorities Students of 1st to 12th class.', 'Social welfare & Empowerment', '{"target_group": ["Scheduled Caste", "Scheduled Tribe", "OBC", "Minorities", "Students"], "education_required": "1st to 12th class", "special_conditions": ["Studying in Government or Aided schools"]}'::jsonb, 'Financial assistance for stationery purchase', ARRAY['Caste certificate', 'School certificate', 'Identity proof'], 'https://www.myscheme.gov.in/schemes/fafps', 'Delhi', 'Social Welfare Department'),

(gen_random_uuid(), 'Financial Assistance For Marriage Of Daughters', 'Provides financial assistance to poor widows for marriage of their daughters and to guardians of orphan girls.', 'Social welfare & Empowerment', '{"target_group": ["Widows", "Orphans", "Women"], "gender_specific": "Female", "special_conditions": ["Poor widows or orphan girls"]}'::jsonb, 'Financial assistance for marriage', ARRAY['Income certificate', 'Widow certificate', 'Identity proof', 'Marriage invitation'], 'https://www.myscheme.gov.in/schemes/famdpwog', 'Delhi', 'Social Welfare Department'),

(gen_random_uuid(), 'Financial Assistance for Higher Studies Abroad', 'Supports SC students for higher education abroad in Engineering, Sciences, and Humanities with up to Rs 20,00,000 for PhD and Rs 10,00,000 for Masters.', 'Education & Learning', '{"target_group": ["Scheduled Caste", "Students"], "income_max": 800000, "education_required": "Masters or PhD", "special_conditions": ["For higher education abroad"]}'::jsonb, 'Up to Rs 20,00,000 for PhD and Rs 10,00,000 for Masters', ARRAY['Caste certificate', 'Income certificate', 'Admission letter', 'Academic certificates'], 'https://www.myscheme.gov.in/schemes/fatssfshsa', 'Delhi', 'Social Welfare Department');
