-- Add remaining Delhi schemes (28 more schemes)
INSERT INTO schemes (id, name, description, category, eligibility_criteria, benefits, required_documents, application_url, state, department) VALUES
(gen_random_uuid(), 'Free Supply of Text Books', 'Provides textbooks or cash subsidies for textbooks and writing materials to students of Government and Aided Schools from Nursery to 12th.', 'Education & Learning', '{"target_group": ["Students"], "education_required": "Nursery to 12th", "special_conditions": ["Students of Government and Aided Schools"]}'::jsonb, 'Financial assistance ranging from Rs 550 to Rs 830 per annum', ARRAY['School certificate', 'Identity proof'], 'https://www.myscheme.gov.in/schemes/fsotb', 'Delhi', 'Education Department'),

(gen_random_uuid(), 'Funeral Assistance for Construction Workers', 'Provides funeral assistance of Rs 10,000 to nominees/dependents in case of death of a registered construction worker.', 'Social welfare & Empowerment', '{"target_group": ["Construction Workers"], "special_conditions": ["Death of registered member"]}'::jsonb, 'Rs 10,000 funeral assistance', ARRAY['Death certificate', 'Registration certificate', 'Nominee documents'], 'https://www.myscheme.gov.in/schemes/facw', 'Delhi', 'Labour Department'),

(gen_random_uuid(), 'Grant for Purchase of Work Related Tools', 'Provides grant to eligible construction workers for purchasing work-related tools.', 'Banking,Financial Services and Insurance', '{"target_group": ["Construction Workers"], "special_conditions": ["Registered with Board for at least 6 months"]}'::jsonb, 'Grant for purchasing work tools', ARRAY['Registration certificate', 'Tool purchase invoice'], 'https://www.myscheme.gov.in/schemes/gpwrtcw', 'Delhi', 'Labour Department'),

(gen_random_uuid(), 'Higher Education And Skill Development Guarantee Scheme', 'Provides financial assistance to students who wish to pursue diploma or degree level courses or specified skill development courses in Delhi.', 'Education & Learning', '{"target_group": ["Students"], "education_required": "Diploma or Degree", "special_conditions": ["For higher education and skill development in Delhi"]}'::jsonb, 'Financial assistance for higher education', ARRAY['Academic certificates', 'Admission letter', 'Income certificate'], 'https://www.myscheme.gov.in/schemes/hesdgs', 'Delhi', 'Education Department'),

(gen_random_uuid(), 'Incentive for Inter-Caste Marriage Scheme', 'Promotes inter-caste marriages between SC and non-SC communities with financial incentive of Rs 50,000.', 'Social welfare & Empowerment', '{"target_group": ["General Public"], "special_conditions": ["Inter-caste marriage between SC and non-SC", "Either spouse permanent resident of Delhi"]}'::jsonb, 'Financial incentive of Rs 50,000', ARRAY['Marriage certificate', 'Caste certificate', 'Identity proof'], 'https://www.myscheme.gov.in/schemes/ificms', 'Delhi', 'Social Welfare Department'),

(gen_random_uuid(), 'Internship Scheme Delhi', 'Allows short-term exposure to youth about working of different sections of the Department of Forests and Wildlife as Interns.', 'Education & Learning', '{"target_group": ["Students", "Youth"], "special_conditions": ["Interest in forestry and wildlife"]}'::jsonb, 'Internship opportunity with stipend', ARRAY['Academic certificates', 'Identity proof', 'Application form'], 'https://www.myscheme.gov.in/schemes/isdelhi', 'Delhi', 'Forests and Wildlife Department'),

(gen_random_uuid(), 'Jai Bhim Mukhyamantri Pratibha Vikas Yojana', 'Provides coaching and stipend to SC students for competitive examinations.', 'Social welfare & Empowerment', '{"target_group": ["Scheduled Caste", "Students"], "special_conditions": ["For competitive examination coaching"]}'::jsonb, 'Coaching and stipend for competitive exams', ARRAY['Caste certificate', 'Academic certificates', 'Identity proof'], 'https://www.myscheme.gov.in/schemes/jbmpvy', 'Delhi', 'Social Welfare Department'),

(gen_random_uuid(), 'Loan for Purchase of Work Tool', 'Provides loan not exceeding Rs 20,000 to construction workers for purchase of work related tools.', 'Banking,Financial Services and Insurance', '{"target_group": ["Construction Workers"], "special_conditions": ["Registered with Board"]}'::jsonb, 'Loan up to Rs 20,000', ARRAY['Registration certificate', 'Tool purchase estimate'], 'https://www.myscheme.gov.in/schemes/lpwtcw', 'Delhi', 'Labour Department'),

(gen_random_uuid(), 'Maternity Assistance for Construction Workers', 'Provides maternity benefits of Rs 30,000 to registered women construction workers and wives of male members for up to 2 children.', 'Health & Wellness', '{"target_group": ["Construction Workers", "Women"], "gender_specific": "Female", "special_conditions": ["For up to 2 children", "Registered with Board"]}'::jsonb, 'Rs 30,000 maternity benefit', ARRAY['Registration certificate', 'Medical certificate', 'Hospital documents'], 'https://www.myscheme.gov.in/schemes/mafcw', 'Delhi', 'Labour Department'),

(gen_random_uuid(), 'Medical Assistance for Construction Workers', 'Provides medical assistance up to Rs 10,000 for hospitalization of 5 or more days due to accident or disease.', 'Health & Wellness', '{"target_group": ["Construction Workers"], "special_conditions": ["Hospitalization for 5 plus days", "Registered with Board"]}'::jsonb, 'Medical assistance up to Rs 10,000', ARRAY['Registration certificate', 'Medical documents', 'Hospital bills'], 'https://www.myscheme.gov.in/schemes/maftcw', 'Delhi', 'Labour Department'),

(gen_random_uuid(), 'Merit Cum Means Linked Financial Assistance Scheme', 'Provides financial assistance to students for high quality higher education in Delhi State Universities irrespective of caste, creed, or economic background.', 'Education & Learning', '{"target_group": ["Students"], "education_required": "Higher Education", "special_conditions": ["Merit cum means based"]}'::jsonb, 'Financial assistance for higher education', ARRAY['Academic certificates', 'Income certificate', 'Admission letter'], 'https://www.myscheme.gov.in/schemes/mcmlfas', 'Delhi', 'Education Department'),

(gen_random_uuid(), 'Mukhyamantri Tirth Yatra Yojana Delhi', 'Provides free pilgrimage to people over 60 years of age.', 'Travel & Tourism', '{"target_group": ["Senior Citizens"], "age_min": 60, "special_conditions": ["Free pilgrimage for senior citizens"]}'::jsonb, 'Free pilgrimage travel', ARRAY['Age proof', 'Identity proof'], 'https://www.myscheme.gov.in/schemes/mtyyd', 'Delhi', 'Tourism Department'),

(gen_random_uuid(), 'Mukhyamantri Vidyarthi Pratibha Yojna', 'Provides scholarships to students studying in classes 9th to 12th.', 'Social welfare & Empowerment', '{"target_group": ["Students"], "education_required": "9th to 12th", "special_conditions": ["Merit-based scholarship"]}'::jsonb, 'Scholarship for classes 9th to 12th', ARRAY['School certificate', 'Academic certificates', 'Identity proof'], 'https://www.myscheme.gov.in/schemes/mvpy', 'Delhi', 'Education Department'),

(gen_random_uuid(), 'Natural Death Assistance for Construction Workers', 'Provides financial assistance of Rs 1,00,000 to nominees/dependents in case of natural death of registered construction worker.', 'Social welfare & Empowerment', '{"target_group": ["Construction Workers"], "special_conditions": ["Natural death of registered worker"]}'::jsonb, 'Rs 1,00,000 financial assistance', ARRAY['Death certificate', 'Registration certificate', 'Nominee documents'], 'https://www.myscheme.gov.in/schemes/ndacw', 'Delhi', 'Labour Department'),

(gen_random_uuid(), 'Old Age Assistance Delhi', 'Provides monthly pension to old age needy persons.', 'Social welfare & Empowerment', '{"target_group": ["Senior Citizens"], "age_min": 60, "special_conditions": ["Needy senior citizens"]}'::jsonb, 'Monthly pension for senior citizens', ARRAY['Age proof', 'Income certificate', 'Identity proof'], 'https://www.myscheme.gov.in/schemes/oaa', 'Delhi', 'Social Welfare Department'),

(gen_random_uuid(), 'Pension Benefit for Construction Workers', 'Provides monthly pension of Rs 3000 to registered construction workers after completion of 60 years.', 'Social welfare & Empowerment', '{"target_group": ["Construction Workers", "Senior Citizens"], "age_min": 60, "special_conditions": ["Registered with Board"]}'::jsonb, 'Monthly pension of Rs 3000', ARRAY['Registration certificate', 'Age proof', 'Identity proof'], 'https://www.myscheme.gov.in/schemes/pbcw', 'Delhi', 'Labour Department'),

(gen_random_uuid(), 'Post Matric Scholarship for SC students Delhi', 'Provides fee reimbursement and monthly allowances to SC students for post-matriculation studies.', 'Education & Learning', '{"target_group": ["Scheduled Caste", "Students"], "income_max": 250000, "education_required": "Post-Matric", "special_conditions": ["For post-matriculation studies"]}'::jsonb, 'Fee reimbursement and monthly allowances', ARRAY['Caste certificate', 'Income certificate', 'Academic certificates', 'Admission letter'], 'https://www.myscheme.gov.in/schemes/pmsfssd', 'Delhi', 'Social Welfare Department'),

(gen_random_uuid(), 'Purchase Construction of House for Construction Workers', 'Provides advance amount of Rs 3,00,000 to Rs 5,00,000 for purchase or construction of house.', 'Housing & Shelter', '{"target_group": ["Construction Workers"], "special_conditions": ["Registered with Board"]}'::jsonb, 'Advance of Rs 3,00,000 to Rs 5,00,000', ARRAY['Registration certificate', 'Property documents', 'Construction estimate'], 'https://www.myscheme.gov.in/schemes/pchcw', 'Delhi', 'Labour Department'),

(gen_random_uuid(), 'Rajiv Gandhi Swavlamban Rojgar Yojna', 'Provides employment opportunities to youths, artisans, trained professionals, skilled technocrats, and entrepreneurs.', 'Business & Entrepreneurship', '{"target_group": ["Youth", "Artisans", "Entrepreneurs"], "special_conditions": ["For self-employment"]}'::jsonb, 'Financial assistance for employment', ARRAY['Identity proof', 'Business plan', 'Qualification certificates'], 'https://www.myscheme.gov.in/schemes/rgsry', 'Delhi', 'Delhi Khadi and Village Industries Board'),

(gen_random_uuid(), 'Reimbursement of Tution Fee for SC ST OBC Min students', 'Provides reimbursement of tuition and compulsory fees for SC/ST/OBC students from low-income families.', 'Education & Learning', '{"target_group": ["Scheduled Caste", "Scheduled Tribe", "OBC", "Students"], "income_max": 300000, "education_required": "Class I to XII", "special_conditions": ["Studying in recognized schools in Delhi"]}'::jsonb, 'Reimbursement of tuition and compulsory fees', ARRAY['Caste certificate', 'Income certificate', 'School certificate', 'Fee receipts'], 'https://www.myscheme.gov.in/schemes/rotffssipsic', 'Delhi', 'Education Department'),

(gen_random_uuid(), 'Scheme for Celebration of Birth death Anniversary', 'Provides financial assistance for celebration of anniversaries of eminent personalities like Dr. B.R. Ambedkar, Sant Kabir, etc.', 'Business & Entrepreneurship', '{"target_group": ["NGOs", "Organizations"], "special_conditions": ["For celebration of anniversaries"]}'::jsonb, 'Financial assistance for celebrations', ARRAY['Organization registration', 'Event proposal', 'Budget estimate'], 'https://www.myscheme.gov.in/schemes/scbdaep', 'Delhi', 'Social Welfare Department'),

(gen_random_uuid(), 'Scholarship Merit Scholarship for College Students', 'Provides monthly financial aid to SC/ST/OBC/Minority students pursuing higher education.', 'Education & Learning', '{"target_group": ["Scheduled Caste", "Scheduled Tribe", "OBC", "Minorities", "Students"], "education_required": "College or Technical or Professional", "special_conditions": ["Based on academic performance and income"]}'::jsonb, 'Monthly scholarships for hostellers and day scholars', ARRAY['Caste certificate', 'Income certificate', 'Academic certificates', 'Admission letter'], 'https://www.myscheme.gov.in/schemes/smssssictpi', 'Delhi', 'Education Department'),

(gen_random_uuid(), 'Scholarship Merit scholarship to OBC MIN SC ST students', 'Provides financial assistance to students from SC/ST/OBC/Minority communities studying in classes I to XII.', 'Education & Learning', '{"target_group": ["Scheduled Caste", "Scheduled Tribe", "OBC", "Minorities", "Students"], "education_required": "Class I to XII", "special_conditions": ["Studying in government or recognised schools"]}'::jsonb, 'Varying scholarship amounts based on class and performance', ARRAY['Caste certificate', 'School certificate', 'Academic certificates'], 'https://www.myscheme.gov.in/schemes/smstomsssfc', 'Delhi', 'Education Department'),

(gen_random_uuid(), 'Subsidy for School Uniforms', 'Provides cash subsidies for school uniforms to students from Nursery to Class XII.', 'Education & Learning', '{"target_group": ["Students"], "education_required": "Nursery to Class XII", "special_conditions": ["Students in government and aided schools"]}'::jsonb, 'Annual payments ranging from Rs 1,100 to Rs 1,500', ARRAY['School certificate', 'Identity proof'], 'https://www.myscheme.gov.in/schemes/sfsutts', 'Delhi', 'Education Department'),

(gen_random_uuid(), 'Transport Loan Scheme Delhi', 'Promotes self-employment by providing term loans for Light Motor Vehicles to SC, OBC, Minorities, and Safai Karamcharis.', 'Transport & Infrastructure', '{"target_group": ["Scheduled Caste", "OBC", "Minorities", "Safai Karamcharis"], "special_conditions": ["For purchase of Light Motor Vehicles"]}'::jsonb, 'Financial assistance up to Rs 5,00,000', ARRAY['Caste certificate', 'Driving license', 'Vehicle purchase estimate'], 'https://www.myscheme.gov.in/schemes/tls-delhi', 'Delhi', 'DSFDC'),

(gen_random_uuid(), 'Viksit Delhi CM Internship Programme', 'Provides internship opportunities to graduation and post-graduation students for policy and decision making.', 'Education & Learning', '{"target_group": ["Students"], "education_required": "Graduation or Post-graduation", "special_conditions": ["For policy and decision making internship"]}'::jsonb, 'Internship with stipend and boot camp', ARRAY['Academic certificates', 'Identity proof', 'Application form'], 'https://www.myscheme.gov.in/schemes/vdcmip', 'Delhi', 'Government of Delhi'),

(gen_random_uuid(), 'Widow Daughter Marriage Scheme', 'Provides financial assistance to widows for marriage of their daughters.', 'Social welfare & Empowerment', '{"target_group": ["Widows", "Women"], "gender_specific": "Female", "special_conditions": ["For marriage of widow daughter"]}'::jsonb, 'Financial assistance for marriage', ARRAY['Widow certificate', 'Income certificate', 'Marriage invitation', 'Identity proof'], 'https://www.myscheme.gov.in/schemes/fawdsddaw', 'Delhi', 'Women and Child Development Department'),

(gen_random_uuid(), 'Yatra Pass in DTC non AC Buses', 'Provides pass of Rs 2400 per three months for non AC DTC bus to registered construction workers.', 'Social welfare & Empowerment', '{"target_group": ["Construction Workers"], "special_conditions": ["Registered with Board"]}'::jsonb, 'Pass of Rs 2400 per three months', ARRAY['Registration certificate', 'Identity proof'], 'https://www.myscheme.gov.in/schemes/ypidnabftcw', 'Delhi', 'Labour Department');
