import crypto from 'crypto';
import fs from 'fs';

// All Maharashtra schemes (40 schemes)
const maharashtraSchemes = [
  { slug: 'aabym', name: 'Aam Aadmi Bima Yojana (Maharashtra)', description: 'The "Aam Aadmi Bima Yojana" scheme is implemented by the Social Justice & Special Assistance Department, Government of Maharashtra. This Centrally Sponsored Scheme is aimed at providing insurance and scholarship benefits to landless labourers in rural areas, aged 18 to 59 years.', category: 'Social welfare & Empowerment', eligibility: '{"age": "18-59", "income": "Below poverty line", "occupation": "Landless labourer", "residency": "Maharashtra resident"}', benefits: 'Insurance and scholarship benefits', url: 'https://www.myscheme.gov.in/schemes/aabym' },
  { slug: 'awvsssi', name: 'Award Of Stipend To VJNT And SBC Students Studying In ITI', description: 'The Government of Maharashtra launched a scheme that provides to encourage Vimukta Jati and Nomadic Tribes (V.J.N.T.) & Special Backward Class (S.B.C.) students and promote the interest in Technical education.', category: 'Social welfare & Empowerment', eligibility: '{"age": "18-35", "category": "VJNT/SBC", "education": "ITI student", "residency": "Maharashtra resident"}', benefits: 'Stipend for ITI students', url: 'https://www.myscheme.gov.in/schemes/awvsssi' },
  { slug: 'bhausaheb-fundkar', name: 'Bhausaheb Fundkar Falbag Lagvad Scheme', description: 'This scheme includes, Plantation of sixteen perennial horticulture crops. Farmer from Konkan division can avail benefit of 0.10 Hector to 10.00 Hector and rest Of Maharashtra 0.20 Hector to 6.00 Hector', category: 'Agriculture,Rural & Environment', eligibility: '{"age": "18-70", "occupation": "Farmer", "land": "0.10-10 hectares", "residency": "Maharashtra resident"}', benefits: 'Direct benefit transfer for horticulture plantation', url: 'https://www.myscheme.gov.in/schemes/bhausaheb-fundkar-horticulture-plantataion-scheme' },
  { slug: 'cmegp', name: 'CHIEF MINISTER EMPLOYMENT GENERATION PROGRAMME (CMEGP)', description: 'Government of Maharashtra has approved the introduction of a new credit linked subsidy program called Chief Minister Employment Generation Program(CMEGP) for generation of employment opportunities through establishment of Micro & Small Enterprises in rural as well as urban areas in state.', category: 'Business & Entrepreneurship', eligibility: '{"age": "18-45", "category": "SC/ST/OBC/Female/PwD/VJNT", "residency": "Maharashtra resident"}', benefits: 'Credit linked subsidy for micro enterprises', url: 'https://www.myscheme.gov.in/schemes/cmegp' },
  { slug: 'chief-minister-irrigation', name: 'Chief Minister Sustainable Agriculture Irrigation Scheme - Magel Tyala Shettale (Individual Farm Pond)', description: 'Under this scheme subsidy payable to individual farmer is minimum Rs.14433/- and maximum Rs.75000/- depending on the size of the farm pond.', category: 'Agriculture,Rural & Environment', eligibility: '{"age": "18-70", "occupation": "Farmer", "residency": "Maharashtra resident"}', benefits: 'Subsidy for farm pond construction (₹14,433 - ₹75,000)', url: 'https://www.myscheme.gov.in/schemes/chief-minister-sustainable-agriculture-irrigation-scheme' },
  { slug: 'cts-maharashtra', name: 'Craftsman Training Scheme - Maharashtra', description: 'The "Craftsman Training Scheme" provides vocational training to individuals, enhancing their skill & employability. This stipend aims to support the trainees financially & encourage them to pursue & complete their vocational training, thereby contributing to skilled manpower development in the state', category: 'Skills & Employment', eligibility: '{"age": "14-40", "education": "8th pass minimum", "residency": "Maharashtra resident"}', benefits: 'Vocational training with stipend', url: 'https://www.myscheme.gov.in/schemes/cts-maharashtra' },
  { slug: 'drpdhma', name: 'Dr. Panjabrao Deshmukh Hostel Maintenance Allowance', description: "This scheme is for the Students whose parent's annual Income is below 800000 and Students whose parents are Marginal Land Holder and registered laborers.", category: 'Education & Learning', eligibility: '{"age": "15-25", "income": "Below ₹8,00,000", "occupation": "Student", "residency": "Maharashtra resident"}', benefits: 'Hostel maintenance allowance', url: 'https://www.myscheme.gov.in/schemes/drpdhma' },
  { slug: 'eafdc', name: 'Educational Assistance for Degree Course', description: 'The Educational Assistance for Degree Course scheme provides financial assistance to children of registered construction workers pursuing their undergraduate degree (1st, 2nd, 3rd, and 4th year, if applicable). This benefit is also extended to the wife of a registered male worker.', category: 'Education & Learning', eligibility: '{"age": "17-25", "occupation": "Construction worker family", "education": "Degree student", "residency": "Maharashtra resident"}', benefits: 'Financial assistance for degree education', url: 'https://www.myscheme.gov.in/schemes/eafdc' },
  { slug: 'eagrdc', name: 'Educational Assistance for Government Recognised Diploma Courses', description: 'The Educational Assistance for Government Recognised Diploma Courses scheme is designed to financially support children of registered construction workers, providing ₹20,000 per year for diploma courses and ₹25,000/- per year for postgraduate diploma courses.', category: 'Education & Learning', eligibility: '{"age": "17-25", "occupation": "Construction worker family", "education": "Diploma student", "residency": "Maharashtra resident"}', benefits: '₹20,000-₹25,000 per year for diploma courses', url: 'https://www.myscheme.gov.in/schemes/eagrdc' },
  { slug: 'eafmaec', name: 'Educational Assistance for Medical and Engineering Courses', description: 'The Maharashtra Building and Other Construction Workers Welfare Board provides educational assistance to the children and spouses of registered construction workers pursuing medical and engineering degrees.', category: 'Education & Learning', eligibility: '{"age": "17-25", "occupation": "Construction worker family", "education": "Medical/Engineering student", "residency": "Maharashtra resident"}', benefits: 'Financial assistance for medical and engineering education', url: 'https://www.myscheme.gov.in/schemes/eafmaec' },
  { slug: 'eatt10t12s', name: 'Educational Assistance to the 10th to 12th Students', description: 'The Educational Assistance to the 10th to 12th Students scheme was launched by the Maharashtra Building And Other Construction Workers Welfare Board (MBOCWW), Labour Department Maharashtra.', category: 'Education & Learning', eligibility: '{"age": "14-19", "occupation": "Construction worker family", "education": "10th-12th student", "residency": "Maharashtra resident"}', benefits: 'Financial assistance for secondary education', url: 'https://www.myscheme.gov.in/schemes/eatt10t12s' },
  { slug: 'eacrws11a12s', name: 'Educational Assistance to the Children of the Registered Worker Studying in 11th and 12th Standard', description: 'The "Educational Assistance" scheme provides financial support of ₹10,000 per year to children of registered construction workers who are studying in the 11th or 12th standard. The benefit applies to a maximum of two children per worker and extends to the wife of a registered male worker.', category: 'Education & Learning', eligibility: '{"age": "15-19", "occupation": "Construction worker family", "education": "11th-12th student", "residency": "Maharashtra resident"}', benefits: '₹10,000 per year for 11th-12th students', url: 'https://www.myscheme.gov.in/schemes/eacrws11a12s' },
  { slug: 'eacs1t7a8t10', name: 'Educational Assistance to the Children Studying in 1st to 7th and 8th to 10th Class', description: 'Under this scheme, educational assistance is provided of ₹2,500/- to the children studying in 1st to 7th standard and ₹5,000/- for the children studying in 8th to 10th standard of the registered construction worker. The scheme covers up to two children and the wife of a registered male worker.', category: 'Education & Learning', eligibility: '{"age": "6-16", "occupation": "Construction worker family", "education": "1st-10th student", "residency": "Maharashtra resident"}', benefits: '₹2,500-₹5,000 per year for school education', url: 'https://www.myscheme.gov.in/schemes/eacs1t7a8t10' },
  { slug: 'faaadp', name: 'Financial Assistance For Aids And Appliances For Disabled Persons', description: 'The "Financial Assistance for Aids and Appliances for Disabled Persons" is a scheme by the Govt. of Maharashtra. The objective of this scheme is to provide assistance to Persons with Disabilities (PwDs) for the purchase of aids and appliances as per their age group and the type of disability.', category: 'Social welfare & Empowerment', eligibility: '{"age": "0-100", "disability": "40% or above", "residency": "Maharashtra resident"}', benefits: 'Financial assistance for aids and appliances', url: 'https://www.myscheme.gov.in/schemes/faaadp' },
  { slug: 'fagcaha18', name: 'Financial Assistance for Girl Child Attend Her Age of 18', description: 'The Financial Assistance for Girl Child Attend Her Age of 18 scheme provides financial assistance in the form of a fixed deposit of ₹1,00,000/- for each female child of a registered worker or spouse who has undergone a family planning operation after the birth of one female child.', category: 'Social welfare & Empowerment', eligibility: '{"age": "18", "gender": "Female", "occupation": "Construction worker family", "residency": "Maharashtra resident"}', benefits: '₹1,00,000 fixed deposit at age 18', url: 'https://www.myscheme.gov.in/schemes/fagcaha18' },
  { slug: 'fafnd', name: 'Financial Assistance for Natural Death', description: 'The scheme "Financial Assistance for Natural Death" was launched by the Maharashtra Building & Other Construction Workers Welfare Board (MBOCWW), Labour Department Maharashtra. Under the scheme, the Board provides financial assistance of ₹2,00,000/- to the legal heir of a registered worker who dies.', category: 'Social welfare & Empowerment', eligibility: '{"occupation": "Construction worker family", "residency": "Maharashtra resident"}', benefits: '₹2,00,000 to legal heir on natural death', url: 'https://www.myscheme.gov.in/schemes/fafnd' },
  { slug: 'fandsd', name: 'Financial Assistance for Normal Delivery and Surgical Delivery', description: 'The "Financial Assistance for Normal Delivery and Surgical Delivery" scheme was launched by the Maharashtra Building And Other Construction Workers Welfare Board (MBOCWW), Labour Department Maharashtra.', category: 'Women and Child', eligibility: '{"gender": "Female", "occupation": "Construction worker family", "residency": "Maharashtra resident"}', benefits: 'Financial assistance for childbirth', url: 'https://www.myscheme.gov.in/schemes/fandsd' },
  { slug: 'fawwrcw', name: 'Financial Assistance for Widow or Widower of Registered Construction Worker', description: 'The scheme is implemented by the Maharashtra Building and Other Construction Workers Welfare Board. Under this scheme, financial assistance of ₹24,000/- p.a. up to 5 years to the widow or widower in case of death of a registered worker during the course of employment.', category: 'Social welfare & Empowerment', eligibility: '{"occupation": "Construction worker family", "marital_status": "Widow/Widower", "residency": "Maharashtra resident"}', benefits: '₹24,000 per year for 5 years', url: 'https://www.myscheme.gov.in/schemes/fawwrcw' },
  { slug: 'fat75opd', name: 'Financial Assistance to 75% or Permanent Disability', description: 'The Financial Assistance to 75% or Permanent Disability was launched by the Maharashtra Building & Other Construction Workers Welfare Board (MBOCWW), Labor Department Maharashtra. In scheme, financial assistance of ₹2,00,000/- to the registered worker in case of 75 % or more permanent disability.', category: 'Social welfare & Empowerment', eligibility: '{"occupation": "Construction worker", "disability": "75% or above", "residency": "Maharashtra resident"}', benefits: '₹2,00,000 for 75% or permanent disability', url: 'https://www.myscheme.gov.in/schemes/fat75opd' },
  { slug: 'fadse', name: 'Financial Assistance To Disabled For Self Employment', description: 'The objective of this scheme is to facilitate the self-employment of unemployed disabled persons. Under this scheme, financial assistance is provided to persons with disabilities for self-employment, small-scale business, and agro-based project. This scheme is 100% funded by Govt. of Maharashtra.', category: 'Skills & Employment', eligibility: '{"age": "18-55", "disability": "40% or above", "residency": "Maharashtra resident"}', benefits: 'Financial assistance for self-employment', url: 'https://www.myscheme.gov.in/schemes/fadse' },
  { slug: 'fatnukyv', name: 'Financial Assistance to Newlyweds under Kanyadan Yojana (Vijabhaj)', description: '"Financial Assistance to Newlyweds under Kanyadan Yojana (Vijabhaj)" was launched by the Dept of Social Justice & Special Assistance, Govt of Maharashtra. The scheme aims to reduce the economic, social, and educational backwardness of Scheduled Castes, Freed Castes, Nomadic Tribes, etc.', category: 'Women and Child', eligibility: '{"age": "18-35", "category": "SC/ST/NT", "residency": "Maharashtra resident"}', benefits: 'Financial assistance for marriage', url: 'https://www.myscheme.gov.in/schemes/fatnukyv' },
  { slug: 'fasetdp', name: 'Financial Assistance To Self-Employment For Trained Disabled Persons', description: 'The "Financial Assistance to Self-Employment for Trained Disabled Persons" is a scheme by the Govt. of Maharashtra. The objective of this scheme is to provide financial assistance to facilitate the purchase of equipment for those disabled persons who are completing their vocational training.', category: 'Social welfare & Empowerment', eligibility: '{"age": "18-55", "disability": "40% or above", "education": "Vocational training completed", "residency": "Maharashtra resident"}', benefits: 'Financial assistance for equipment purchase', url: 'https://www.myscheme.gov.in/schemes/fasetdp' },
  { slug: 'fsme', name: 'First Self Marriage Expenses', description: 'The Maharashtra Building and Other Construction Workers Welfare Board implemented the "First Self Marriage Expenses" scheme. Under this scheme, financial assistance of ₹30,000/- towards the first self marriage expenses to the registered worker.', category: 'Social welfare & Empowerment', eligibility: '{"age": "18-35", "occupation": "Construction worker", "residency": "Maharashtra resident"}', benefits: '₹30,000 for first marriage', url: 'https://www.myscheme.gov.in/schemes/fsme' },
  { slug: 'fa', name: 'Funeral Assistance', description: 'Under this scheme, the "Maharashtra Building & Other Construction Workers Welfare Board" (MBOCWW) provides financial assistance for funeral expenses of ₹10,000/- to the nominated heir of the deceased registered worker in the event of their death.', category: 'Social welfare & Empowerment', eligibility: '{"occupation": "Construction worker family", "residency": "Maharashtra resident"}', benefits: '₹10,000 for funeral expenses', url: 'https://www.myscheme.gov.in/schemes/fa' },
  { slug: 'gopinath-munde', name: 'Gopinath Munde Shetkari Apghat Suraksha Sanugrah Audhan Yojana', description: 'In order to give financial support to the aggrieved family members of the ill-fated farmers the State Govt. has provided accident claim cover through Gopinath Munde Shetkari Apghat Suraksha Sanugrah Audhan Yojana in the year 2023-24.', category: 'Agriculture,Rural & Environment', eligibility: '{"age": "18-70", "occupation": "Farmer", "residency": "Maharashtra resident"}', benefits: 'Accident insurance cover for farmers', url: 'https://www.myscheme.gov.in/schemes/gopinath-munde-shetkari-apghat-suraksha-sanugrah-audhan-yojana' },
  { slug: 'gaoah', name: 'Grant In Aid To Old Age Home', description: 'The "Grant in Aid to Old Age Home" is a scheme by the Dept. of Social Justice & Special Assistance, Govt. of Maharashtra. In this scheme, grants are provided to the NGOs for accommodating old men & women, destitute, disabled victims, into Old Age Homes, and providing them with food, & accommodation.', category: 'Housing & Shelter', eligibility: '{"age": "60-100", "income": "Below poverty line", "residency": "Maharashtra resident"}', benefits: 'Grant for old age home accommodation', url: 'https://www.myscheme.gov.in/schemes/gaoah' },
  { slug: 'gsgos', name: 'Group Supply Of Goats And Sheep', description: 'Group supply of goats and sheep refers to the practice of selling or distributing goats and sheep in groups, rather than as individual animals. In Maharashtra, this practice is common among farmers, livestock traders, and cooperative organizations.', category: 'Business & Entrepreneurship', eligibility: '{"age": "18-60", "category": "Tribal", "occupation": "Farmer/Livestock trader", "residency": "Maharashtra resident"}', benefits: 'Group supply of goats and sheep', url: 'https://www.myscheme.gov.in/schemes/gsgos' },
  { slug: 'hiip', name: 'Homes For Intellectually Impaired Persons', description: 'The "Homes for Intellectually Impaired Persons" is a scheme by the Department of Social Justice & Special Assistance, Govt. of Maharashtra. In this scheme, Mentally Deficient Children who are in need of care and protection are admitted into shelter homes through the Child Welfare Committees.', category: 'Housing & Shelter', eligibility: '{"age": "0-18", "disability": "Intellectual impairment", "residency": "Maharashtra resident"}', benefits: 'Shelter home for intellectually impaired children', url: 'https://www.myscheme.gov.in/schemes/hiip' },
  { slug: 'igteicm', name: 'Incentive given to Encourage Inter caste Marriages', description: 'The "Incentive for Encouraging Inter-Caste Marriages" scheme is implemented by the Department of Social Justice & Special Assistance, Government of Maharashtra, and funded jointly by the State and Central Government (50:50). The scheme provides financial incentives to support inter-caste marriages.', category: 'Women and Child', eligibility: '{"age": "18-35", "residency": "Maharashtra resident"}', benefits: 'Financial incentive for inter-caste marriage', url: 'https://www.myscheme.gov.in/schemes/igteicm' },
  { slug: 'igndpsm', name: 'Indira Gandhi National Disability Pension Scheme (Maharashtra)', description: 'The "Indira Gandhi National Disability Pension Scheme (Maharashtra)" is implemented by the Social Justice & Special Assistance Dept., Govt. of Maharashtra. The differently-abled individuals aged 18 to 65 years with a disability of 80% and above are eligible to receive a pension of ₹600/- per month.', category: 'Social welfare & Empowerment', eligibility: '{"age": "18-65", "disability": "80% or above", "income": "Below poverty line", "residency": "Maharashtra resident"}', benefits: '₹600 per month pension', url: 'https://www.myscheme.gov.in/schemes/igndpsm' },
  { slug: 'igoapsm', name: 'Indira Gandhi National Old Age Pension Scheme (Maharashtra)', description: 'The scheme "Indira Gandhi National Old Age Pension" is a social welfare scheme by the Social Justice & Special Assistance Department, Government of Maharashtra. In this scheme, ₹600 per month is provided to elderly individuals aged 65 years and above from BPL families.', category: 'Social welfare & Empowerment', eligibility: '{"age": "65-100", "income": "Below poverty line", "residency": "Maharashtra resident"}', benefits: '₹600 per month pension', url: 'https://www.myscheme.gov.in/schemes/igoapsm' },
  { slug: 'ignwpsm', name: 'Indira Gandhi National Widow Pension Scheme (Maharashtra)', description: '"Indira Gandhi National Widow Pension Scheme (Maharashtra)" is a scheme by the Social Justice & Special Assistance Dept, Govt of Maharashtra. In this scheme, widows aged 40 to 79 years who are from a BPL family receive a pension of ₹1500/- per month.', category: 'Social welfare & Empowerment', eligibility: '{"age": "40-79", "gender": "Female", "marital_status": "Widow", "income": "Below poverty line", "residency": "Maharashtra resident"}', benefits: '₹1,500 per month pension', url: 'https://www.myscheme.gov.in/schemes/ignwpsm' },
  { slug: 'kvdgssy', name: 'Karma Veer Dadasaheb Gaikwad Sabalikaran & Swabhiman Yojana', description: 'The main objective of this scheme is to improve the financial condition of the scheduled castes and Nav-Buddhists who are landless workers and are from "Below Poverty Line". Only citizens who are permanent residents of Maharashtra are eligible. This scheme is 100% funded by the State Govt.', category: 'Agriculture,Rural & Environment', eligibility: '{"age": "18-60", "category": "SC/Nav-Buddhist", "income": "Below poverty line", "occupation": "Landless worker", "residency": "Maharashtra resident"}', benefits: 'Loan and subsidy for landless workers', url: 'https://www.myscheme.gov.in/schemes/kvdgssy' },
  { slug: 'kpdgbcpd', name: 'Karmaveer Padmashri Dadasaheb Gaikwad Birth Centenary And Prize Distribution', description: 'The "Karmaveer Padmashri Dadasaheb Gaikwad Birth Centenary and Prize Distribution" is an award by the Govt. of Maharashtra. The award is given to individuals and organizations working for the social movement against traditional customs and untouchability and for landless farm workers.', category: 'Social welfare & Empowerment', eligibility: '{"residency": "Maharashtra resident"}', benefits: 'Award for social work', url: 'https://www.myscheme.gov.in/schemes/kpdgbcpd' },
  { slug: 'l50ss', name: 'LIDCOM 50% Subsidy Scheme', description: 'The "50% Subsidy Scheme" is a scheme by LIDCOM, Govt. of Maharashtra. In this scheme, 50% amount is being given as a subsidy on a maximum loan amount of ₹50,000/-. The subsidy is subject to the maximum limit of ₹10,000/-. The bank charge of interest is as per the existing rate.', category: 'Banking,Financial Services and Insurance', eligibility: '{"age": "18-55", "category": "Charmakar community", "residency": "Maharashtra resident"}', benefits: '50% subsidy on loan up to ₹10,000', url: 'https://www.myscheme.gov.in/schemes/l50ss' },
  { slug: 'lels', name: 'LIDCOM Education Loan Scheme', description: 'The "Education Loan Scheme" is a scheme by the Leather Industries Development Corporation (LIDCOM), Govt. of Maharashtra. In this scheme, finance of upto ₹ 20,00,000 is provided for post graduate students in the 18-50 years age group from Charmakar Community for studies in India and in abroad.', category: 'Education & Learning', eligibility: '{"age": "18-50", "category": "Charmakar community", "education": "Post-graduate student", "residency": "Maharashtra resident"}', benefits: 'Education loan up to ₹20,00,000', url: 'https://www.myscheme.gov.in/schemes/lels' },
  { slug: 'lgss', name: 'LIDCOM Gattai Stall Scheme', description: 'Being implemented by LIDCOM, Govt. of Maharashtra for the Roadsides Cobblers from the (Scheduled Caste) Charmakar Community, this scheme provides a 100% subsidy for the erection of a Tin Stall of Size 4′ x 5′ x 6.5′ costing ₹16367/- per stall and ₹500/- incidental charges.', category: 'Business & Entrepreneurship', eligibility: '{"age": "18-60", "category": "Charmakar community", "occupation": "Cobbler", "residency": "Maharashtra resident"}', benefits: '100% subsidy for tin stall (₹16,867)', url: 'https://www.myscheme.gov.in/schemes/lgss' },
  { slug: 'lmmls', name: 'LIDCOM Margin Money Loan Scheme', description: 'In this scheme, for a loan limit from ₹50,001 to ₹5,00,000/-, 20% of the Project cost loan as Seed Capital is paid by the Corporation @ 4% interest per annum. A maximum of ₹10,000/- will be paid as a subsidy by Corporation. A 5% amount of project cost will have to be contributed by the beneficiary.', category: 'Banking,Financial Services and Insurance', eligibility: '{"age": "18-55", "category": "Charmakar community", "residency": "Maharashtra resident"}', benefits: 'Margin money loan with subsidy', url: 'https://www.myscheme.gov.in/schemes/lmmls' },
  { slug: 'lts', name: 'LIDCOM Training Scheme', description: 'Being implemented particularly for the Charmakar Community, the "Training Scheme" is a scheme by the Leather Industries Development Corporation (LIDCOM), Govt. of Maharashtra. This scheme is being implemented for the students to enable them to start their own businesses, trade, or get a job.', category: 'Business & Entrepreneurship', eligibility: '{"age": "18-35", "category": "Charmakar community", "residency": "Maharashtra resident"}', benefits: 'Vocational training for business/employment', url: 'https://www.myscheme.gov.in/schemes/lts' }
];

// All West Bengal schemes (29 schemes)
const westBengalSchemes = [
  { slug: 'ismpsscis', name: 'Incentive Scheme for MSMEs in Powerloom Sector: State Capital Investment Subsidy', description: '"State Capital Investment Subsidy" incentives under "Incentive Scheme for MSMEs in Powerloom Sector" scheme implemented by the Dept. of MSME & T, Government of West Bengal, aims to provide subsidy of the fixed capital investment made for its approved project.', category: 'Business & Entrepreneurship', eligibility: '{"age": "18-65", "occupation": "MSME owner", "sector": "Powerloom", "residency": "West Bengal resident"}', benefits: 'State capital investment subsidy', url: 'https://www.myscheme.gov.in/schemes/ismpsscis' },
  { slug: 'wbisaito', name: 'The West Bengal Incentive Scheme: Additional Incentive for Adventure Tour Operators', description: '"Additional Incentive for Adventure Tour Operators" incentives under the "WBIS" scheme by the Dept. of Tourism, Government of West Bengal, aims to provide reimbursement incentives with SGST payments for purchasing tents, dinghies, adventure & sports equipment, and related accessories.', category: 'Business & Entrepreneurship', eligibility: '{"age": "18-65", "occupation": "Tour operator", "sector": "Adventure tourism", "residency": "West Bengal resident"}', benefits: 'SGST reimbursement for adventure equipment', url: 'https://www.myscheme.gov.in/schemes/wbisaito' },
  { slug: 'wbisaige', name: 'The West Bengal Incentive Scheme: Additional Incentive on Generation of Employment', description: '"Additional Incentive on Generation of Employment" incentives under "The West Bengal Incentive Scheme" scheme by the Dept. of Tourism, Government of West Bengal, aims to provide reimbursement of expenditure incurred for paying contribution towards ESI and EPF.', category: 'Business & Entrepreneurship', eligibility: '{"age": "18-65", "occupation": "Tourism unit owner", "residency": "West Bengal resident"}', benefits: 'ESI and EPF contribution reimbursement', url: 'https://www.myscheme.gov.in/schemes/wbisaige' },
  { slug: 'wbiscu', name: 'The West Bengal Incentive Scheme: Capacity Utilisation', description: '"Capacity Utilisation" incentives under the "The West Bengal Incentive Scheme" implemented by the Dept. of Tourism, Government of West Bengal, aims to provide additional Floor Area Ratio (FAR) over and above the maximum permissible FAR as may be fixed by the competent authority.', category: 'Business & Entrepreneurship', eligibility: '{"age": "18-65", "occupation": "Tourism unit owner", "residency": "West Bengal resident"}', benefits: 'Additional Floor Area Ratio (FAR)', url: 'https://www.myscheme.gov.in/schemes/wbiscu' },
  { slug: 'wbisistl', name: 'The West Bengal Incentive Scheme: Interest Subsidy on Term Loan', description: '"Interest Subsidy on Term Loan" incentives under "The West Bengal Incentive Scheme" scheme by the Dept. of Tourism, Government of West Bengal, aims to provide Interest Subsidy on annual interest liability on the Term Loan borrowed from a Bank to an approved project of an eligible unit.', category: 'Business & Entrepreneurship', eligibility: '{"age": "18-65", "occupation": "Tourism unit owner", "residency": "West Bengal resident"}', benefits: 'Interest subsidy on term loan', url: 'https://www.myscheme.gov.in/schemes/wbisistl' },
  { slug: 'wbisrsdrf', name: 'The West Bengal Incentive Scheme: Reimbursement of Stamp Duty and Registration Fee', description: '"Reimbursement of Stamp Duty and Registration Fee" incentives under the "WBIS" scheme implemented by the Dept. of Tourism, Government of West Bengal, aims to provide a reimbursement of stamp duty and registration fee paid by the eligible units for the purpose of registration of documents.', category: 'Business & Entrepreneurship', eligibility: '{"age": "18-65", "occupation": "Tourism unit owner", "residency": "West Bengal resident"}', benefits: 'Stamp duty and registration fee reimbursement', url: 'https://www.myscheme.gov.in/schemes/wbisrsdrf' },
  { slug: 'wbisscis', name: 'The West Bengal Incentive Scheme: State Capital Investment Subsidy', description: '"State Capital Investment Subsidy" incentives under "The West Bengal Incentive Scheme" scheme implemented by the Dept. of Tourism, Government of West Bengal, aims to provide a State Capital Investment Subsidy of the fixed capital investment.', category: 'Business & Entrepreneurship', eligibility: '{"age": "18-65", "occupation": "Tourism unit owner", "residency": "West Bengal resident"}', benefits: 'State capital investment subsidy', url: 'https://www.myscheme.gov.in/schemes/wbisscis' },
  { slug: 'wbissqi', name: 'The West Bengal Incentive Scheme: Subsidy for Quality Improvement', description: '"Subsidy for Quality Improvement" incentives under the "WBIS" scheme aims to provide a reimbursement for the fixed capital investment expenditure incurred for quality improvement, modernization and installation of pollution control devices and for obtaining ISI/BIS/ISO certification.', category: 'Business & Entrepreneurship', eligibility: '{"age": "18-65", "occupation": "Tourism unit owner", "residency": "West Bengal resident"}', benefits: 'Quality improvement subsidy', url: 'https://www.myscheme.gov.in/schemes/wbissqi' },
  { slug: 'wbistpais', name: 'The West Bengal Incentive Scheme: Tourism Promotion Assistance in lieu of Interest Subsidy', description: '"Tourism Promotion Assistance in lieu of Interest Subsidy" incentive under the "The West Bengal Incentive Scheme" aims to provide Tourism Promotion Assistance for SGST irrespective of the location of the project, which will be in lieu of interest subsidy.', category: 'Business & Entrepreneurship', eligibility: '{"age": "18-65", "occupation": "Tourism unit owner", "residency": "West Bengal resident"}', benefits: 'Tourism promotion assistance (SGST)', url: 'https://www.myscheme.gov.in/schemes/wbistpais' },
  { slug: 'wbiswed', name: 'The West Bengal Incentive Scheme: Waiver of Electricity Duty', description: '"Waiver of Electricity Duty" incentives under "The West Bengal Incentive Scheme" scheme implemented by the Dept. of Tourism, Government of West Bengal, aims to provide waiver of electricity duty on the electricity consumed in its approved project.', category: 'Business & Entrepreneurship', eligibility: '{"age": "18-65", "occupation": "Tourism unit owner", "residency": "West Bengal resident"}', benefits: 'Electricity duty waiver', url: 'https://www.myscheme.gov.in/schemes/wbiswed' },
  { slug: 'wbtisiee', name: 'West Bengal Textile Incentive Scheme: Incentive for Energy Efficiency', description: '"Incentive for Energy Efficiency" incentives under "West Bengal Textile Incentive Scheme" scheme implemented by the Dept. of MSME&T, Government of West Bengal, aims to provide a reimbursement for the cost of energy and installations for energy conservation as per energy audit.', category: 'Business & Entrepreneurship', eligibility: '{"age": "18-65", "occupation": "Textile unit owner", "residency": "West Bengal resident"}', benefits: 'Energy efficiency incentive', url: 'https://www.myscheme.gov.in/schemes/wbtisiee' },
  { slug: 'wbisps', name: 'West Bengal Textile Incentive Scheme: Power Subsidy', description: '"Power Subsidy" incentives under "West Bengal Textile Incentive Scheme" scheme implemented by the Dept. of MSME&T, Government of West Bengal, aims to provide power subsidy on electricity consumption for 5 years from the date of commencement of production.', category: 'Business & Entrepreneurship', eligibility: '{"age": "18-65", "occupation": "Textile unit owner", "residency": "West Bengal resident"}', benefits: 'Power subsidy for 5 years', url: 'https://www.myscheme.gov.in/schemes/wbisps' },
  { slug: 'wbtisscis', name: 'West Bengal Textile Incentive Scheme: State Capital Investment Subsidy', description: '"State Capital Investment Subsidy" incentives under "West Bengal Textile Incentive Scheme" scheme implemented by the Dept. of MSME&T, Government of West Bengal, aims to provide a State Capital Investment Subsidy of the fixed capital investment.', category: 'Business & Entrepreneurship', eligibility: '{"age": "18-65", "occupation": "Textile unit owner", "residency": "West Bengal resident"}', benefits: 'State capital investment subsidy', url: 'https://www.myscheme.gov.in/schemes/wbtisscis' },
  { slug: 'wbtisswcec', name: 'West Bengal Textile Incentive Scheme: Subsidy for Water conservation/ Environment Compliance', description: '"Subsidy for Water Conservation/ Environment Compliance" incentives under "West Bengal Textile Incentive Scheme" scheme by the Dept. of MSME&T , Government of West Bengal, aims to provide reimbursement of expenditure incurred by it towards the cost of captive Effluent Water Treatment Plant.', category: 'Business & Entrepreneurship', eligibility: '{"age": "18-65", "occupation": "Textile unit owner", "residency": "West Bengal resident"}', benefits: 'Water conservation/environment compliance subsidy', url: 'https://www.myscheme.gov.in/schemes/wbtisswcec' },
  { slug: 'wbtiswed', name: 'West Bengal Textile Incentive Scheme: Waiver of Electricity Duty', description: '"Waiver of Electricity Duty" incentives under "West Bengal Textile Incentive Scheme" scheme implemented by the Dept. of MSME&T, Government of West Bengal, aims to provide waiver of electricity duty on the electricity consumed in its approved project.', category: 'Business & Entrepreneurship', eligibility: '{"age": "18-65", "occupation": "Textile unit owner", "residency": "West Bengal resident"}', benefits: 'Electricity duty waiver', url: 'https://www.myscheme.gov.in/schemes/wbtiswed' },
  { slug: 'wbtiswfflcm', name: 'West Bengal Textile Incentive Scheme: Waiver of Fees for Land Conversion and Mutation', description: '"Waiver of Fees for Land Conversion and Mutation" incentives under "West Bengal Textile Incentive Scheme" scheme implemented by the Dept. of MSME&T, Government of West Bengal, aims to provide a waiver of fees for conversion and mutation of the land as approved in the project.', category: 'Business & Entrepreneurship', eligibility: '{"age": "18-65", "occupation": "Textile unit owner", "residency": "West Bengal resident"}', benefits: 'Land conversion and mutation fee waiver', url: 'https://www.myscheme.gov.in/schemes/wbtiswfflcm' },
  { slug: 'adwb', name: 'Accidental Benefit', description: 'The "Accidental Benefit" scheme by the BOCW Welfare Board, Labour Department,West Bengal, is a welfare scheme that provides financial assistance to the beneficiary in case of hospitalization and disability due to an accident.', category: 'Social welfare & Empowerment', eligibility: '{"age": "18-60", "occupation": "Construction worker", "residency": "West Bengal resident"}', benefits: 'Financial assistance for accident', url: 'https://www.myscheme.gov.in/schemes/adwb' },
  { slug: 'ahs', name: 'Akanksha Housing Scheme', description: 'Akanksha Housing Scheme was launched by the Housing Department, Government of West Bengal on 28/02/2014 to provide housing to the serving State Government employees.', category: 'Housing & Shelter', eligibility: '{"age": "25-58", "occupation": "State government employee", "residency": "West Bengal resident"}', benefits: 'Housing for state government employees', url: 'https://www.myscheme.gov.in/schemes/ahs' },
  { slug: 'bay', name: 'Banglar Awaas Yojana (BAY)', description: '"Banglar Awaas Yojana (BAY)" provides financial assistance to houseless households and those living in kutcha or dilapidated houses, helping them build pucca houses with essential amenities. The scheme offers financial assistance with additional support for toilets and unskilled workdays.', category: 'Housing & Shelter', eligibility: '{"income": "Below poverty line", "housing": "Houseless/kutcha house", "residency": "West Bengal resident"}', benefits: 'Financial assistance for pucca house construction', url: 'https://www.myscheme.gov.in/schemes/bay' },
  { slug: 'byswb', name: 'Banglar Yuba Sathi', description: 'The scheme aims to provide monthly financial assistance to educated unemployed youth of West Bengal to support them until they get employment or join another scheme. The objective is to ensure income support for eligible unemployed youth for a maximum period of 5 years.', category: 'Social welfare & Empowerment', eligibility: '{"age": "18-45", "education": "Graduate/Post-graduate", "employment": "Unemployed", "residency": "West Bengal resident"}', benefits: 'Monthly allowance for unemployed youth (max 5 years)', url: 'https://www.myscheme.gov.in/schemes/byswb' },
  { slug: 'bis', name: 'Banglashree for Micro, Small and Medium Enterprises: Interest Subsidy on Term Loan (IS)', description: '"Interest Subsidy on Term Loan (IS)" incentives under "Banglashree for MSMEs" scheme implemented by the MSMEs Dept., Government of West Bengal, aims to provide Interest Subsidy on annual interest liability on the Term Loan borrowed from a Commercial Bank to an eligible micro or small enterprise.', category: 'Business & Entrepreneurship', eligibility: '{"age": "18-65", "occupation": "MSME owner", "residency": "West Bengal resident"}', benefits: 'Interest subsidy on term loan', url: 'https://www.myscheme.gov.in/schemes/bis' },
  { slug: 'bmsmeps', name: 'Banglashree for Micro, Small and Medium Enterprises: Power Subsidy (PS)', description: '"Power Subsidy (PS)" incentives under "Banglashree for MSMEs" scheme implemented by the MSMEs Dept., Government of West Bengal, aims to provide power subsidy on the electricity consumed for the manufacturing activity to an eligible micro or small enterprise.', category: 'Business & Entrepreneurship', eligibility: '{"age": "18-65", "occupation": "MSME owner", "residency": "West Bengal resident"}', benefits: 'Power subsidy for manufacturing', url: 'https://www.myscheme.gov.in/schemes/bmsmeps' },
  { slug: 'cis', name: 'Banglashree for Micro, Small and Medium Enterprises: State Capital Investment Subsidy (CIS)', description: '"State Capital Investment Subsidy (CIS)" incentives under "Banglashree for MSMEs" scheme implemented by the MSMEs Department, Government of West Bengal, aims to provide Capital Investment Subsidy for its approved project to an eligible micro or small enterprise.', category: 'Business & Entrepreneurship', eligibility: '{"age": "18-65", "occupation": "MSME owner", "residency": "West Bengal resident"}', benefits: 'State capital investment subsidy', url: 'https://www.myscheme.gov.in/schemes/cis' },
  { slug: 'ees', name: 'Banglashree for Micro, Small and Medium Enterprises: Subsidy for Energy Efficiency (EES)', description: '"Subsidy for Energy Efficiency (EES)" incentives under "Banglashree for MSMEs" scheme implemented by the MSMEs Dept., Government of West Bengal, aims to provide a reimbursement for the cost of energy and installations for energy conservation as per energy audit.', category: 'Business & Entrepreneurship', eligibility: '{"age": "18-65", "occupation": "MSME owner", "residency": "West Bengal resident"}', benefits: 'Energy efficiency subsidy', url: 'https://www.myscheme.gov.in/schemes/ees' },
  { slug: 'bmsmeprs', name: 'Banglashree for Micro, Small and Medium Enterprises: Subsidy for Patent Registration (PRS)', description: '"Subsidy for Patent Registration (PRS)" incentives under "Banglashree for MSMEs" scheme implemented by the MSMEs Dept., Government of West Bengal, aims to provide reimbursement of expenditure incurred for obtaining Patent Registration.', category: 'Business & Entrepreneurship', eligibility: '{"age": "18-65", "occupation": "MSME owner", "residency": "West Bengal resident"}', benefits: 'Patent registration subsidy', url: 'https://www.myscheme.gov.in/schemes/bmsmeprs' },
  { slug: 'bmsmesccs', name: 'Banglashree for Micro, Small and Medium Enterprises: Subsidy for Standard Quality Compliance (SCCS)', description: '"Subsidy for Standard Quality Compliance (SCCS)" incentives under "Banglashree for MSMEs" scheme implemented by the MSMEs Dept., Government of West Bengal, aims to provide reimbursement of the expenditure incurred for obtaining certification from approved Institutions/ Research Laboratories.', category: 'Business & Entrepreneurship', eligibility: '{"age": "18-65", "occupation": "MSME owner", "residency": "West Bengal resident"}', benefits: 'Quality compliance certification subsidy', url: 'https://www.myscheme.gov.in/schemes/bmsmesccs' },
  { slug: 'bmsmesgst', name: 'Banglashree for Micro, Small and Medium Enterprises: Subsidy for State Goods and Services Tax (SGST)', description: '"Subsidy for State Goods and Services Tax (SGST)" incentives under "Banglashree for MSMEs" scheme implemented by the MSMEs Dept., Government of West Bengal, aims to provide refunds for net SGST paid to the Government of West Bengal.', category: 'Business & Entrepreneurship', eligibility: '{"age": "18-65", "occupation": "MSME owner", "residency": "West Bengal resident"}', benefits: 'SGST refund', url: 'https://www.myscheme.gov.in/schemes/bmsmesgst' },
  { slug: 'bmsmewcs', name: 'Banglashree for Micro, Small and Medium Enterprises: Subsidy for Water Conservation/Environment Compliance (WCS)', description: '"Subsidy for Water Conservation/Environment Compliance" incentives by the MSMEs Dept., Government of West Bengal, aims to provide reimbursement of expenditure incurred by it towards the cost of captive Effluent Water Treatment Plant for wastewater recycling and/ or other pollution control devices.', category: 'Business & Entrepreneurship', eligibility: '{"age": "18-65", "occupation": "MSME owner", "residency": "West Bengal resident"}', benefits: 'Water conservation/environment compliance subsidy', url: 'https://www.myscheme.gov.in/schemes/bmsmewcs' },
  { slug: 'bmsmewwas', name: 'Banglashree for Micro, Small and Medium Enterprises: Subsidy for Work Force Welfare Assistance (WWAS)', description: '"Subsidy for Work Force Welfare Assistance (WWAS)" incentives under "Banglashree for MSMEs" scheme implemented by the MSMEs Dept., Government of West Bengal, aims to provide reimbursement of expenditure incurred for paying contribution towards Employees State Insurance (ESI) and Employees Provident.', category: 'Business & Entrepreneurship', eligibility: '{"age": "18-65", "occupation": "MSME owner", "residency": "West Bengal resident"}', benefits: 'ESI and EPF contribution reimbursement', url: 'https://www.myscheme.gov.in/schemes/bmsmewwas' }
];

// Generate SQL
let sql = `-- Batch 5: Add 69 schemes (40 Maharashtra + 29 West Bengal) with UUID format
-- Generated on ${new Date().toISOString()}

INSERT INTO schemes (id, name, description, state, category, eligibility_criteria, benefits, required_documents, application_url)
VALUES
`;

const allSchemes = [...maharashtraSchemes, ...westBengalSchemes];

const values = allSchemes.map((scheme, index) => {
  const uuid = crypto.randomUUID();
  const isLast = index === allSchemes.length - 1;
  return `('${uuid}', '${scheme.name.replace(/'/g, "''")}', '${scheme.description.replace(/'/g, "''")}', '${scheme.slug.includes('wb') || westBengalSchemes.includes(scheme) ? 'West Bengal' : 'Maharashtra'}', '${scheme.category}', '${scheme.eligibility}'::jsonb, '${scheme.benefits}', NULL, '${scheme.url}')${isLast ? ';' : ','}`;
}).join('\n');

sql += values;

// Write to file
fs.writeFileSync('/workspace/app-adfkyk0iayo1/supabase/migrations/add_schemes_batch5_uuid.sql', sql);

console.log('✅ Migration file generated successfully!');
console.log(`📊 Total schemes: ${allSchemes.length}`);
console.log(`   - Maharashtra: ${maharashtraSchemes.length}`);
console.log(`   - West Bengal: ${westBengalSchemes.length}`);
console.log('📁 File: supabase/migrations/add_schemes_batch5_uuid.sql');
